### ISSUE TITLE
Qual palestrante você gostaria de ouvir ?

### ISSUE THREAD

**Issue by guisouza** [nodebr/nodeconfbr#1]
vamos trazer gente zica ..  

eu queria ouvir o Eran Hammer

**Comment by joaostein** [comment]
+1 @joeyyang -- what do you think? :)

**Comment by joeyyang** [comment]
@joaostein haha yes i'm in!

**Comment by Pompeu** [comment]
Palestra do Pedro falando do pagar.me?
Aplicação node no mundo Real 
aquale do Rupy foi muito show....

**Comment by gustavodemari** [comment]
Eran Hamer, Walmart, hapi.js (@hueniverse)
Pedro Franceschi, Pagar.me (@pedrofranceschi)
Fedor Indutny, Node.js, io.js (@indutny)
Jeff Harrell, Paypal (@jeffharrell)
Roger Wang, Node-webkit/NW.js (@rogerwang)
Douglas Christopher Wilson, Express.js (@dougwilson)
Caio Ribeiro Pereira, Aplicações web real-time com Node.js (@caio-ribeiro-pereira)

**Comment by suissa** [comment]
Se não trouxer ele eu nem vou :p 
Max Ogden https://github.com/maxogden

**Comment by marcosbergamo** [comment]
Galera, montei uma lista com os 4 primeiros + comentados ai da lista e serão os que eu irei entrar em contato para ver se eles tem disponibilidade de vir para a nossa 1º NodeConfBR seguem os nomes:

Forrest L Norvell    (@othiym23) - San Franscisco - USA
Eram Hammer       (@hueniverse) - Los Gatos - USA
Fedor Indutny	      (@indutny) - Russia
Julian Duque	      (@julianduque) - Medellín - Colombia 

Como o levantamento foi feito?
Na reunião de ontem ficou definido que teríamos 4 palestras de estrangeiros, e o restante das palestras seria ministrada por nós Brasileiros para nós valorizarmos nossos desenvolvedores nacionais também, tem muita coisa acontecendo aqui com os BRs também =D

Assim que estes me responderem dou um parecer aqui =D

**Comment by caio-ribeiro-pereira** [comment]
So tem feras na lista e eu de fraco kkk de qualquer forma obrigado por me
adicionarem na lista!

Preciso saber quando e onde sera esse evento, pra confirmar se poderei
palestrar,  vlw!

**Comment by ericdouglas** [comment]
Nicolas Bevacqua ( @bevacqua )

**Comment by marcosbergamo** [comment]
Sobre a lista acima convites enviados, vamos aguardar a resposta e se for o caso uma segunda rodada de emails =D

**Comment by fernandoGuisso** [comment]
Popcorn Time
Pagar.me (@pedrofranceschi)
Jean Carlo Nascimento(@suissa)

**Comment by marcosbergamo** [comment]
Sabe me dizer o nome do cara do popcorn?

**Comment by romuloigor** [comment]
Ja me manifestei pelo face no post do Eric mas vou reproduzir aqui! gostaria de ver algo sobre a infraestrutura do server Node.JS em producao para projetos grandes ... de preferencia infra em nuvem pois o custo é menor ... estou estudando o Amazon Lambda para rodar meus projetos Node com infra performatica e pensando no Disaster Recovery do server Node.  segue um video que fiz  sobre o assunto http://youtu.be/NAGK5xGVDNo

**Comment by ericdouglas** [comment]
@romuloigor +1

**Comment by jacksonfdam** [comment]
@romuloigor +2

**Comment by obetomuniz** [comment]
(@debergalis) Matt Debergalis

**Comment by pablojuancruz** [comment]
@suissa

**Comment by julianduque** [comment]
@marcellodesales Brazilian doing node in the enterprise, also micro services, containers, and such

**Comment by marcellodesales** [comment]
@julianduque Is highly recommended as well!!! (right back to you buddy)... Julian has helped Intuit along with NodeSource to improve our Production environments. I definitely would love to be present. I'm interested in focusing on Node.js Micro-services in Docker.

**Comment by fernandoGuisso** [comment]
@nodebots

**Comment by jeanleonino** [comment]
+1 @ee99ee

**Comment by jeanleonino** [comment]
@

**Comment by ee99ee** [comment]
Would love to be part of this
