### ISSUE TITLE
Domínio para o evento

### ISSUE THREAD

**Issue by alanhoff** [nodebr/nodeconfbr#13]
Pessoal, alguém conhece o dono do nodeconf.com.br? Gostaríamos de saber se ele estaria disposto a apontas o DNS aqui para o GitHub.

**Comment by obetomuniz** [comment]
boa @gblmarquez  :smile:

**Comment by alanhoff** [comment]
Na reunião de hoje decidimos por usar conf.nodebr.org/2015
