### ISSUE TITLE
Comitê de Organização 

### ISSUE THREAD

**Issue by marcosbergamo** [nodebr/nodeconfbr#15]
Galera, como já estamos caminhando bem, talvez possamos já começar a nós organizar para escolher um comitê para que essas pessoas possam se disponibilizar para dar mais foco ao nosso tão desejado evento. 
Claro que nossa maior premissa é um evento orientado pela comunidade e esses digamos cabeças iram ajudar a concluir as metas e sugestões de todos para que possamos ter a melhor NodeConf do ano =D (sonhar faz bem hehe)

**Comment by estudio86** [comment]
Galera, tentei, vocês podem verificar se está correto? 

https://github.com/estudio86/nodeconfbr/blob/master/comite/template.md

**Comment by marcosbergamo** [comment]
Só trocar o nome de template.md para {nome do comitê}-{primeiro nome}-{ultimo nome}.md =D

**Comment by estudio86** [comment]
opa, vou lá tentar haha @marcosbergamo

**Comment by estudio86** [comment]
Mudei. Tudo certinho agora @marcosbergamo ? =D

**Comment by ericdouglas** [comment]
@estudio86 dá uma olhadinha [aqui](https://github.com/nodebr/nodeconfbr/tree/master/comite) nos outros para você ter uma base.

O nome do seu arquivo vai ficar `PP-JoaoPauloRodrigues.md`

**Comment by estudio86** [comment]
Valeu @ericdouglas, acho que agora foi haha

**Comment by ericdouglas** [comment]
Agora foi mesmo @estudio86 ! 

Só mandar o pull request para esse repositório :smile:

**Comment by estudio86** [comment]
Blz @ericdouglas, como faço isso? haha

**Comment by ericdouglas** [comment]
@estudio86 veja se te ajuda: [link](https://help.github.com/articles/creating-a-pull-request/)

**Comment by dalssoft** [comment]
@heitortsergent boa! :)

**Comment by suissa** [comment]
Tem mais alguma coisa po tio aqui fazer?

**Comment by marcosbergamo** [comment]
Comite de PP precisa de gente =D

**Comment by estudio86** [comment]
@marcosbergamo Então, eu tenho uma agência de publicidade, com equipe de design, front e backend, então seria tranquilo tocar os trabalhos, mas, é tranquilo se mais alguém quiser participar também. Estou só com um pouco de dificuldade  no Github para dar o Fork e o Pull Request lá, ainda, mesmo com o @suissa fazendo um vídeo para me ajudar e tal haha ... Desculpem a ignorância nesse caso, mas, eu nunca usei o Git para nada então, to apanhando aqui ainda haha

**Comment by marcosbergamo** [comment]
@estudio86 estou redigindo um email agora para você =D

**Comment by estudio86** [comment]
@marcosbergamo respondi lá rapaz!

**Comment by marcosbergamo** [comment]
vamo que vamo!

**Comment by GarciaSouza** [comment]
Pessoal, boa tarde! Há algo em que eu possa contribuir ainda? Já há informação de quando/onde será a próxima reunião?

**Comment by suissa** [comment]
PP é bem isso que sei fazer :dancers:

**Comment by alanhoff** [comment]
+1 suissa

**Comment by fernandoGuisso** [comment]
Falando em PP, sera que rola um Self-Checkin?

**Comment by alanhoff** [comment]
Algum exemplo disto Luís?


--
Alan Hoffmeister
https://twitter.com/alan_hoff
https://github.com/alanhoff
https://keybase.io/alanhoff

2015-01-24 13:21 GMT-02:00 Luís Fernando Guisso Filho <
notifications@github.com>:

**Comment by suissa** [comment]
@estudio86 o que precisar é só dar um toque man que é nois ;)

**Comment by fernandoGuisso** [comment]
O participante recebe um QRCode por email alguns dias antes do evento, no dia, ele chega e apresenta o QRCode para um receptor(Um computar do camera), ele verifica e imprime uma etiqueta com os dados do participante, ele cola no cracha que vem no kit conf.
Eu vi isso no GDG DevFest de 2013, @luisleao que fez, não vi como funciona, mas acho q ele tem um repositorio sobre

**Comment by luisleao** [comment]
https://github.com/luisleao/self-checkin

Fui eu sim. No luisleao.com.br/checkin dá pra testar com a planilha de testes que tem no Github. Só manter a chave-primária (e-mail ou o que for no QRCode) e o nome da segunda coluna. Estou pra modificar o código de forma que as configurações de layout do checkin e da etiqueta fiquem na própria planilha. Daí qualquer um pode usar essa minha url.

Uso isso desde 2012 e já fiz evento com ele para 600 pessoas e rolou de boa. Precisa de uma máquina que suporte o plugin da Dymo e tenha a impressora Label Writer 450.

Vocês vão fazer isso quando? Me passa detalhes no e-mail luis.leao [arroba] gmail.

**Comment by alanhoff** [comment]
Caraca que ideia bacana! Será que alguém poderia ajudar com esse hardware?

**Comment by fernandoGuisso** [comment]
Eu posso, sempre tive curiosidade de ver como a coisa funciona.
