### ISSUE TITLE
só palestra ?

### ISSUE THREAD

**Issue by guisouza** [nodebr/nodeconfbr#2]
Estava pensando em abrir um 'early-bird' onde, quem comprasse, teria a oportunidade de participar de um mini hackaton sob a coordenção dos palestrantes, para ter a oportunidade de interagir, e ouvir conselhos dos caras.

**Comment by jeanleonino** [comment]
+1

Pensando no lado financeiro, poderíamos ter alguém bancando um hackathon, não?

**Comment by IgorDePaula** [comment]
+1

2015-01-28 16:47 GMT-02:00 Jean <notifications@github.com>:

**Comment by fernandoGuisso** [comment]
@IgorDePaula +1 Arduino + Node *-*

@jeanleonino +1 Hackaton
