### ISSUE TITLE
Reunião 19-01-2015 - 1º Milestone

### ISSUE THREAD

**Issue by marcosbergamo** [nodebr/nodeconfbr#25]
Salve Galera!

Estou criando esse tópico aqui com o Objetivo de marcarmos nossa primeira Reunião de "Staff" para que possamos dar continuidade a esse projeto. Sei que ainda é começo do ano, todo mundo ainda aquecendo para esse ano que está chegando, mas temos que correr para fazer um fantastico e memorável evento =D

Estou tomando a liberdade de escolher essa data, por simples motivo de "gostaria que pudessemos falar disso logo para começarmos a correr", mas caso haja alguma restrição fiquem a vontade para remarcar, mas acho que está na hora de voltarmos a ativa.

A ideia da Reunião é ser via Hangout, aberto para qualquer um que queria assistir.

Bom o que acham da data, do meio de comunicação e etc? A opinião de vocês é muito bem vinda =D

@dalssoft , @heitortsergent , @alanhoff , @ericdouglas , @gblmarquez , @paulohp , @guisouza

**Comment by ericdouglas** [comment]
@marcosbergamo por mim tudo bem! :+1:

**Comment by willianjedai** [comment]
@marcosbergamo Pra mim está ok tb.

**Comment by dalssoft** [comment]
bora! qual o horário?

**Comment by paulohp** [comment]
Excelente :D estou dentro, claro.

**Comment by marcosbergamo** [comment]
Em relação ao horario estava pensando em 19h o que acham?

**Comment by gblmarquez** [comment]
Perfeito!

**Comment by ericdouglas** [comment]
:+1:

**Comment by heitortsergent** [comment]
:+1: @marcosbergamo cria um evento no google calendar com o link do hangout e envia pra galera?

**Comment by marcosbergamo** [comment]
https://plus.google.com/u/0/events/cnjd91n3go35jvan03go9poiei4 - Ta na mão o link -D Já criei o evento.

**Comment by alanhoff** [comment]
Pessoal entrem neste link https://hangoutsapi.talkgadget.google.com/hangouts/_/grxzx2umft2ocne43tqshpjptua
