### ISSUE TITLE
Ata Reunião 19-01-2015

### ISSUE THREAD

**Issue by gblmarquez** [nodebr/nodeconfbr#26]
# Ata Reunião 19-01-2015

## Participantes
@ericdouglas @dalssoft @alanhoff @marcosbergamo @willianjedai @paulohp @gblmarquez @heitortsergent

## Quem vai fazer o que?
@dalssoft: ajudar no levantamento dos custos de infra 
@marcosbergamo: landing page, definir programação, palestrantes e levantar custos de viagem e hospedagem, divulgar links de sugestão de palestrantes
@willianjedai: procurar local e levantar custos de infra
@ericdouglas: fixar link para sugestão de palestrantes no facebook, criar planilha base para levamento dos custos
@gblmarquez: criar planilha base para levamento dos custos

## Assunto
- Falta de pessoas para os comitês em geral, temos que convidar outras pessoas para fechar as equipes do comitê, para termos redundância.
- Falta definir o comitê de "Publicidade e propaganda"
- Falta de pessoas não é impeditivo para inicio do planejamento e tarefas em geral.
- Objetivos planejamento:
 - Número de participantes: **200 pessoas**
 - Programação: 
    - Horário do evento: 9h as 18h30
    - Frames: 45min e 2x 5min lightning talks
    - Precisar ser 2 dias de evento para usar o nome NodeConf: http://nodeconf.com/conduct.html
    - Cronograma: ![image](https://cloud.githubusercontent.com/assets/367279/5808716/c52b0d8c-a017-11e4-9eb1-c0550df1a046.png)
 - Definir palestrantes
   - Custo de viagens
   - Call for papers
 - Definir local
    - Estudo do Auditório da Telefônica na Av. Paulista
    - Estudo do Auditório da Scup
- Financeiro
  - Não vamos emitir nfs
  - Usar cartase ou similar para captação da grana (com 13%)
- Levantamento de custos
   - Estimativa de orçamento de 30K
   - Aluguel de local
   - Aluguel da internet
   - Aluguel de áudio
   - Aluguel de vídeo
   - Aluguel de mobiliário (caso necessário)
   - Streaming
   - Comidas e bebidas para palestrantes
   - Coffee-break
   - Pulseiras para credenciamento
   - Mais custos???

**Comment by heitortsergent** [comment]
@wupsbr poderia nos ajudar? :) Estamos procurando local, quais são os requisitos para realizar um evento no auditório da Telefônica?

**Comment by dalssoft** [comment]
@gblmarquez @willianjedai   temos uma issue sobre os fornecedores e os orçamentos? Só pra gente coordenar o esforço de levantar os custos

**Comment by marcosbergamo** [comment]
Acho que seria uma boa criar @dalssoft !

**Comment by willianjedai** [comment]
Mais tarde eu vou criar com algumas infos sobre local

**Comment by marcosbergamo** [comment]
+1 @willianjedai
