### ISSUE TITLE
Proposta de Programação  do Evento

### ISSUE THREAD

**Issue by marcosbergamo** [nodebr/nodeconfbr#27]
Olá Galera!

Estou postando uma proposta para o formato do evento conforme a reunião no dia 19/01.

Teremos os seguintes espaços na programação: 
* 4 Palestrantes Convidados da Comunidade Node.js Internacional
* 4 Palestras Convidados da Comunidade Node.js no Brasil
* 6 Palestrantes da Comunidade (Call4Papers)
*  24 Micro Talks (Call4Papers)

## Programação

Abbr | Descrição
------ | ------------
BR   | Brasileiro
NBR | Não Brasileiro

### Dia 5 de Setembro

Horário | Tipo Palestra | Palestrante | Tempo Estimado
--------- | ----------------- | -------------- | -----------------------
08h00  | **Credenciamento** | --- | 1h00
09h00  | Full Talk | Palestrante Convidado(BR)  | 45min
09h45  | Micro Talk | Call4Papers  | 5min 
09h50  | Micro Talk | Call4Papers  | 5min 
10h00  | Full Talk | Palestrante Convidado(NBR)  | 45min
10h45  | Micro Talk | Call4Papers  | 5min
10h50  | Micro Talk | Call4Papers  | 5min 
11h00  | Full Talk | Call4Papers  | 45min
11h45  | Micro Talk | Call4Papers  | 5min
11h50  | Micro Talk | Call4Papers  | 5min 
12h00  | **Almoço** | --- | 1h30
13h40  | Full Talk | Call4Papers | 45min
14h25 | Micro Talk | Call4Papers | 5min
14h30  | Micro Talk | Call4Papers  | 5min
14h40  | Full Talk | Palestrante Convidado(BR) | 45min
15h25 | Micro Talk | Call4Papers | 5min
15h30  | Micro Talk | Call4Papers  | 5min
15h40  | **Lanche** | --- | 30min
16h10  | Full Talk | Call4Papers | 45min
16h55 | Micro Talk | Call4Papers | 5min
17h00  | Micro Talk | Call4Papers  | 5min
17h05  | Full Talk | Palestrante Convidado(NBR) | 45min
17h50 | **Fechamento** | Mensagem da Comunidade NodeBR

### Dia 6 de Setembro

Horário | Tipo Palestra | Palestrante | Tempo Estimado
--------- | ----------------- | -------------- | -----------------------
08h00  | **Credenciamento** | --- | 1h00
09h00  | Full Talk | Palestrante Convidado(BR)  | 45min
09h45  | Micro Talk | Call4Papers  | 5min 
09h50  | Micro Talk | Call4Papers  | 5min 
10h00  | Full Talk | Palestrante Convidado(NBR)  | 45min
10h45  | Micro Talk | Call4Papers  | 5min
10h50  | Micro Talk | Call4Papers  | 5min 
11h00  | Full Talk | Call4Papers  | 45min
11h45  | Micro Talk | Call4Papers  | 5min
11h50  | Micro Talk | Call4Papers  | 5min 
12h00  | **Almoço** | --- | 1h30
13h40  | Full Talk | Call4Papers | 45min
14h25 | Micro Talk | Call4Papers | 5min
14h30  | Micro Talk | Call4Papers  | 5min
14h40  | Full Talk | Palestrante Convidado(NBR) | 45min
15h25 | Micro Talk | Call4Papers | 5min
15h30  | Micro Talk | Call4Papers  | 5min
15h40  | **Lanche** | --- | 30min
16h10  | Full Talk | Call4Papers | 45min
16h55 | Micro Talk | Call4Papers | 5min
17h00  | Micro Talk | Call4Papers  | 5min
17h05  | Full Talk | Palestrante Convidado(BR) | 45min
17h50 | **Encerramento da Conferência** | Mensagem da Comunidade NodeBR

**Comment by obetomuniz** [comment]
@marcosbergamo Com relação as micro talks, você não acha que está mt apertado o tempo entre uma e outra não? Penso pelo fato de que deva existir um tempo para por exemplo o palestrante configurar o computador, ou outros possíveis problemas que possam aparecer... Eu reduziria pra 12 micro talks, dando intervalo de 5 minutos entre cada uma delas. Não sei como foi definido, mas seria minha primeira alteração no momento.

**Comment by renatoargh** [comment]
Concordo com @obetomuniz está me parecendo bem apertado

**Comment by marcosbergamo** [comment]
Então @obetomuniz levantamos esse problema, mas para essas micro talks, nós da organização iremos meio que já deixar tudo pronto. Seria um computador especial para elas já preparado, o cara simplesmente vai usar sem dores de cabeça.

**Comment by obetomuniz** [comment]
@marcosbergamo Entendi, só acredito não ser muito natural. Deixar o palestrante a vontade, é sempre melhor nesses casos, as vezes ele quer dar algum demo ou coisa do tipo do computador dele, mas se já foi pensado anteriormente, ignora :+1:

**Comment by marcosbergamo** [comment]
Mas nesse caso @obetomuniz acho que a gente pode chamar o palestrante e fazer um aquecimento antes do pessoal chegar, tipo antes das palestras do almoço a gente já faz o teste e resolve possíveis bugs e na volta do almoço idem.

**Comment by obetomuniz** [comment]
Show então @marcosbergamo :smile: :+1:

**Comment by victorferraz** [comment]
Sugiro um coffee break antes do evento, isso é muito bom para o pessoal que vem de fora e está acabando de chegar na cidade...
Também acho que poderia triar a microtalk, geralmente 5min é o tempo do palestrante chegar e configurar seu pc.
Poderia ter um aquecimento como @marcosbergamo  falou,  tipo uma entrevista  antes da talk igual no BrazilJS.

**Comment by afucher** [comment]
Apenas uma coisa para se levar em consideração, vi em outros eventos o pessoal colocar um espaço de 5/10 minutos entre as palestras. Assim caso alguma atrase, não irá impactar em outra... Se não vira uma bola de neve, e quando vai ver as ultimas palestras tem que correr para tentar não acabar muito depois do horário do evento...

Tipo assim:

09h00	Full Talk	Palestrante Convidado(BR)	45min
09h50	Micro Talk	Call4Papers	5min

**Comment by marcosbergamo** [comment]
@afucher temos 5 minutos de espaço entre uma talk e outra. No caso do espaço aproveitando a msg do @victorferraz as Micro Talks por serem menores vai haver uma triagem legal para garantir o tempo das mesmas e iremos sempre deixar os aparelhos na agulha pro palestrante fazer tipo um hot swap =D

**Comment by afucher** [comment]
@marcosbergamo pela grade que está la em cima não parece.. pois talk tem 5min e é exatamente o tempo entre uma e outra... a menos que eu tenha visto errado  ;P

**Comment by marcosbergamo** [comment]
09h00 Full Talk Palestrante Convidado(BR) 45min
---- Talk termina as 09h45 ----
09h50 Micro Talk Call4Papers 5min

No caso desse exemplo entre 09h45 e as 09h50 rola o intervalo de 5 minutos hehe

**Comment by afucher** [comment]
Então, mas eu mudei pra colocar no comentario.... lá em cima não esta assim...

**Comment by marcosbergamo** [comment]
Hum... serio? :p Desculpa cara, não tinha visto :(

Vou corrigir isso a noite =D

**Comment by afucher** [comment]
@marcosbergamo eu achei que eu tava ficando louco hauhauhauhaa

fmza!  =D

**Comment by marcosbergamo** [comment]
#vamoquevamo se quiser acho que você consegue alterar. Sinta-se a vontade para mandar um PR também pro comitê de Progamação, estamos precisando de gente!
