### ISSUE TITLE
Brasileiros Convidados, quem você gostaria de ver?

### ISSUE THREAD

**Issue by marcosbergamo** [nodebr/nodeconfbr#29]
Olá Pessoal!

Como visto nesta issue #27  iremos ter 4 brasileiros convidados para dar palestras, além dos call4papers. Quem, referência na comunidade de Node no Brasil vocês gostariam de ver?

**Comment by IgorDePaula** [comment]
Escolhemos 1 ou escolhemos 4 dat contam-se os votos por cada um e icam os 4
mais votados?

Em 23 de janeiro de 2015 09:55, Marcos Vinicius Bérgamo <
notifications@github.com> escreveu:

**Comment by alanhoff** [comment]
Acho que podem escolher quantos quiserem hehehe :P

**Comment by marcosbergamo** [comment]
Só falar quem você quer ver independente de números. Ai os 4 mais comentados a gente convida =D

**Comment by IgorDePaula** [comment]
votar sem uma lista pra mim vai ser osso, conhecou pouca gente da
comunidade so aqui do grupo mesmo, e mesmo assim, o google grupos nao
mostra os membros..vou listar os q lembro o nome, alan hoffmeister, marcos
bergamo, rodrigo matheus, paulo diovani

2015-01-23 9:59 GMT-02:00 Marcos Vinicius Bérgamo <notifications@github.com>
:

**Comment by dancasttro** [comment]
Olá o Caio Ribeiro Pereira é um nome legal? Ele tem um livro sobre.

**Comment by IgorDePaula** [comment]
eu quero votar no caio tambem...

Em 25 de janeiro de 2015 16:23, Daniel Castro <notifications@github.com>
escreveu:

**Comment by alanhoff** [comment]
Acho bacana dar prioridade para cases do Node.js no Brasil, o @emerleite poderia falar sobre a implementação do Node.js na Globo.com, etc...

**Comment by marcosbergamo** [comment]
+1 @alanhoff

**Comment by obetomuniz** [comment]
+1 @alanhoff

**Comment by alanhoff** [comment]
Se eu não me engano a Vizir na época do @dalssoft botou no ar alguns sistemas com Node.js, acho que ele poderia nos indicar aqui alguns cases, talvez não precisamos botar no palco um programador Node.js, mas sim um dono de empresa dizendo o quanto o Node.js ajudou(ou não :P) o negócio deles, mostrando como era o antes e o depois.

**Comment by ericdouglas** [comment]
+3 @alanhoff

**Comment by obetomuniz** [comment]
Fico com programadores por enquanto...Meus votos vão pra Alan Hoffmeister (@alanhoff), Caio Ribeiro (@caio-ribeiro-pereira) e Emerson Macedo (@emerleite)

E com relação a apresentação de cases por não programadores, acho ótimo, desde que sejam referências de fato :D Porque caso contrário, qualquer empresa que utilize Node, poderia também ter esse espaço, o que claro, depende apenas de votos aqui :smile: ...Mas é bom deixar isso claro mesmo.

**Comment by marcosbergamo** [comment]
Meus votos vão como os do Beto Muniz. Se quiser  posso falar tb de como sai do ódio mortal por js até o amor incondicional hehe

**Comment by antonellisantos** [comment]
@suissa

**Comment by luizstacio** [comment]
@suissa +1

**Comment by MichelSousa** [comment]
@suissa

**Comment by Ibanheiz** [comment]
@suissa
Fiz workshop de MEAN com ele, monstro!

**Comment by suissa** [comment]
@guisouza

**Comment by cazlu8** [comment]
@suissa

**Comment by andrewsmoraes** [comment]
Quero ver o @suissa!!! BE MEAN!!!

**Comment by guiseek** [comment]
@suissa

**Comment by mateuspv** [comment]
@suissa @caio-ribeiro-pereira @alanhoff

**Comment by ceelsoin** [comment]
@suissa sempre!

**Comment by VanessaSoares** [comment]
@suissa

**Comment by caio1989** [comment]
@suissa

**Comment by mazulo** [comment]
@suissa

**Comment by elizeumatheus** [comment]
@suissa

**Comment by acauamontiel** [comment]
@suissa

**Comment by gisellecarvalho** [comment]
@suissa

**Comment by rodolphoo** [comment]
@suissa

**Comment by MarceloBritoWD** [comment]
@alanhoff

**Comment by cristopher-rodrigues** [comment]
@suissa

**Comment by cristianounix** [comment]
@suissa

**Comment by erickjones** [comment]
Claro que é o @suissa

**Comment by felipemarques** [comment]
@suissa

**Comment by GuilhermeARibeiro** [comment]
@suissa

**Comment by Craveiiro** [comment]
@suissa

**Comment by fernandoGuisso** [comment]
@suissa +1
Tb fiz o WK Be MEAN, mt bom!

Virou até issue agora kkk

**Comment by IgorDePaula** [comment]
Suissa, eh um bom nome tambem.

2015-01-26 8:50 GMT-02:00 Luís Fernando Guisso Filho <
notifications@github.com>:

**Comment by brunoskonrad** [comment]
@suissa

**Comment by BrunoKinoshita** [comment]
@suissa

**Comment by willianjusten** [comment]
Voto no @suissa, @alanhoff e @caio-ribeiro-pereira.

**Comment by woliveiras** [comment]
@suissa,  @alanhoff

**Comment by estudio86** [comment]
@suissa @alanhoff @guisouza

**Comment by guilherme22** [comment]
@alanhoff @guisouza e @caio-ribeiro-pereira

**Comment by osamuca** [comment]
@suissa

**Comment by dalssoft** [comment]
IMHO, eu acho muito importante falar de algo que está rodando, em produção, feito aqui no Brasil. Meu voto vai pra quem eu conheço que já fez isso:

Aqui no Scup temos o @willianjedai @tgthies @guisouza @neocite @ (acho que vou esquecer de alguém....) 

Pessoal da Vizir com experiência de colocar sistemas grandes Node.js em produção : @antonioams @diegonakamashi @FabricioFFC @apantaliao @legiao @chagasaway @lucaslimasouza @paulofelisbino

Rico.com.vc: @filipedeschamps @airroom @MarcosRava

Os demais já receberam voto o suficiente :)

**Comment by erkobridee** [comment]
@suissa @caio-ribeiro-pereira

**Comment by chucky6** [comment]
@suissa

**Comment by padilhalucas** [comment]
@suissa

**Comment by grippado** [comment]
@suissa

**Comment by jrxmember2** [comment]
@suissa

**Comment by mateus-paegle** [comment]
@suissa @caio-ribeiro-pereira

**Comment by FabricioFFC** [comment]
@alanhoff temos alguns cases com o pessoal da Rico.com.vc, vou falar com o @filipedeschamps pra montar uma apresentação sobre eles, e principalmente como a cultura/ecossistema da comunidade mudou a rotina de trabalho deles e está trazendo resultados pra empresa

**Comment by willianjedai** [comment]
@alanhoff @guisouza

**Comment by ferfelis** [comment]
@suissa

**Comment by ndesigner** [comment]
@suissa @guisouza

**Comment by antonioams** [comment]
Eu posso fazer uma palestra falando sobre a nossa decisão há 2 anos atrás na Vizir de focar bastante em Javascript e nesse período já colocamos mais  de 5 projetos com feitos em node em produção para empresas como Scup, Rico.vc e Voitel. 

Nesta palestra posso dar um panorama da decisão de focar em Node e quais foram as dificuldades, erros, acertos, vantagens e desvantagens de usar Node em cada um dos projetos.

**Comment by Pompeu** [comment]
@suissa @caio-ribeiro-pereira @LucianoRamalho

**Comment by suissa** [comment]
Muito bom hein @antonioams !!!

**Comment by suissa** [comment]
Luciano Ramalho EH MESTRE DEMAIS!!!!! Mas o user dele @Pompeu é @ramalho

**Comment by Pompeu** [comment]
Mestrão Luciano @ramalho é Lendario Cavaleiro !! #fan

**Comment by ramalho** [comment]
Na verdade o meu nick no Twitter é @ramalhoorg.

Eu agradeço muito a menção, Suissa, mas eu não estou trabalhando com
Node.js no momento.

Valeu!

[ ]s
Luciano

On Mon, Jan 26, 2015 at 4:23 PM, Jean Carlo Nascimento <
notifications@github.com> wrote:

> Luciano Ramalho EH MESTRE DEMAIS!!!!! Mas o user dele @Pompeu
> <https://github.com/Pompeu> é @ramalho <https://github.com/ramalho>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodebr/nodeconfbr/issues/29#issuecomment-71509878>.
>



-- 
Luciano Ramalho
Twitter: @ramalhoorg

Professor em: http://python.pro.br
Twitter: @pythonprobr

**Comment by suissa** [comment]
@ramalho a marcação era do github mesmo não do Twitter hehehehe.

Uma pena mestre pq suas palestras são as melhores!

**Comment by ramalho** [comment]
Legal, valeu, Suissa!

Muito grato pelo elogio.

Estou aqui estudando o módulo asyncio [1] do Python 3.4 que promete ser a
resposta do Python ao Node... promete, mas o ecosistema de biblitotecas
usando asyncio não chega nem a 1% do que existe no Node.

[1] https://docs.python.org/3/library/asyncio.html

[ ]s
Luciano



2015-01-26 18:05 GMT-02:00 Jean Carlo Nascimento <notifications@github.com>:

> @ramalho <https://github.com/ramalho> a marcação era do github mesmo não
> do Twitter hehehehe.
>
> Uma pena mestre pq suas palestras são as melhores!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodebr/nodeconfbr/issues/29#issuecomment-71527867>.
>



-- 
Luciano Ramalho
Twitter: @ramalhoorg

Professor em: http://python.pro.br
Twitter: @pythonprobr

**Comment by rmdias** [comment]
@suissa

**Comment by filipedeschamps** [comment]
Será que aquele pessoal do grupo de meteor seria legal chamar? Os caras já fizeram umas soluções bem legais.

**Comment by graubassauro** [comment]
@suissa @caio-ribeiro-pereira

**Comment by DouglasHennrich** [comment]
@suissa +1

**Comment by gustavomodena** [comment]
@suissa

**Comment by danielrohers** [comment]
@rodrigok meteor forever

**Comment by renatogravino** [comment]
@suissa

**Comment by gustavodemari** [comment]
@pedrofranceschi @caio-ribeiro-pereira @suissa

**Comment by filipedeschamps** [comment]
Boa @gustavodemari... os caras do pagar.me precisam palestrar.

**Comment by ericdouglas** [comment]
@suissa 
@pedrofranceschi
@hdubugras
@romuloigor 

+1 na proposta do @dalssoft

**Comment by guisouza** [comment]
opa pessoal !  
como vão ? 
confesso que tive um tempo meio away da organização devido a outros projetos
que no momento não podem esperar, ví que alguns me indicaram para uma possível
talk durante o evento  ! ..  
venho aqui deixar claro que caso isso aconteça, farei o possível para trazer o melhor conteúdo
possível para essa talk, venho tocando meus projetinhos JS a todo vapor.. 

O pessoal lá no @scup sabe que eu falo deste evento desde sempre e tenho um imenso carinho
por esse projeto desde as primeiras conversas com o @alanhoff, @legiao, @willianjedai, @dalssoft  e o @paulohp .

PS : Logo logo o @updatesemwhere volta de férias.
estamos só resolvendo alguns probleminhas de logística,equipamentos etc ..

**Comment by BielRibeiro** [comment]
+1 @suissa

**Comment by mizunachan** [comment]
@suissa

**Comment by osamuca** [comment]
@suissa

**Comment by mateuspv** [comment]
Já tem @suissa  suficiente pra encher 3 dias de talks

**Comment by suissa** [comment]
E palestra eu tenho para encher 3 dias hehehehhehe #brinks

**Comment by suissa** [comment]
O que que eu posso fazer se ensino Node há 4 anos neh galera? ;)

**Comment by jeanleonino** [comment]
+1 @alanhoff
+1 @suissa 
@emerleite

**Comment by airroom** [comment]
+1 @filipedeschamps

**Comment by MarcosRava** [comment]
@filipedeschamps @dalssoft

**Comment by FabricioFFC** [comment]
+1 @airroom @MarcosRava @filipedeschamps e @legiao

**Comment by marcellodesales** [comment]
Ola, meu nome eh Marcello de Sales, sou Engenheiro da Intuit, USA e trabalho no desenvolvimento de Plataforma de Serviços. Há quase 1 ano, meu time vem trabalhando com vários times desenvolvendo serviços para o Intuit TurboTax e Intuit Quickbooks criando novos serviços em Node.js... Nosso time diretamente criou de conceito a deployment os seguintes casos:

* `Micro-Services` em Node.js;
* Estratégias de compartilhamento de modulos and `repositórios privados NPM` e `dependências em Git` (GitHub Enterprise, Atlessian Stash e GitLabs);
* Fluxo de Processo ágil CI/CD sem/com Docker (Ambientes Dev, QA, Stage, Prod)
 * Jenkins + Manual/Mesos Clusters em Data Centers privado
 * CodeShip/Shippable/CircleCI + Heroku
 * Amazon CodeDeploy + EC2 (objetivo de 2015).

Se houver interesse, gostaria de apresentar em algum desses tópicos... Teremos dois arquitetos apresentando no NodeSummit e estarei presente... Caso algum brasileiro venha para o congresso, e queira discutir, favor enviar msg.

Valeu!

**Comment by renatogalvao** [comment]
@guisouza @suissa @alanhoff

**Comment by jeanleonino** [comment]
+1 @marcellodesales 
+1 @alanhoff 

:-) 

Quando vamos contar e fechar a thread? Até para o pessoal parar de votar no @suissa hehe

**Comment by alanhoff** [comment]
-1 @alanhoff


--
Alan Hoffmeister
https://twitter.com/alan_hoff
https://github.com/alanhoff
https://keybase.io/alanhoff

2015-02-03 11:29 GMT-02:00 Jean <notifications@github.com>:

**Comment by MarceloBritoWD** [comment]
@guisouza

**Comment by erickjones** [comment]
![suissa](https://cloud.githubusercontent.com/assets/1272620/6061691/deb5a566-ad30-11e4-86b8-90d8319d06a5.png)

**Comment by danilovaz** [comment]
@suissa @guisouza

**Comment by suissa** [comment]
Quero saber a contagem depois ehehhehe

**Comment by GuilhermeARibeiro** [comment]
@suissa

**Comment by victorferraz** [comment]
@guisouza  @emerleite

**Comment by MarceloBritoWD** [comment]
@guisouza

**Comment by stewones** [comment]
@suissa

**Comment by leandroprog** [comment]
@suissa

**Comment by suissa** [comment]
Ta e ai quais são os mais votados?

**Comment by suissa** [comment]
Quem irá palestrar?

**Comment by jeanleonino** [comment]
@suissa A versão deste ano da conferência não irá acontecer, logo irei fechar o tópico. Caso tenha dúvidas/feedback, pode falar comigo pessoal, via twitter (@aleattorium) ou via Slack da NodeBR (@jean).
