### ISSUE TITLE
Temas para palestras

### ISSUE THREAD

**Issue by ericdouglas** [nodebr/nodeconfbr#30]
Pessoal, acho mais interessante fazermos primeiro um levantamento dos temas que a comunidade quer ouvir.

Pensei em começarmos fazendo um levantamento dos tópicos mais pedidos, e depois ver quem está disposto a falar sobre tal tema.

Depois disso seria a parte da votação, caso haja várias pessoas querendo falar sobre o mesmo tema.

Ficaria algo assim:

## 1. Comunidade sugere os temas

Se tivermos espaço para 10 temas, e forem sugeridos 30, ai passamos para:

## 2. Escolha (votação) dos temas

Os 10 temas (dos 30) mais votados serão os que os palestrantes deverão falar.

## 3. Interessados em palestrar

Nessa etapa, as pessoas que tiverem interesse em palestrar sobre os tópicos escolhidos, mandarão as informações dizendo porque devem ser escolhidas para tal.

Podemos criar um formulário básico, onde os candidatos deverão mandar informações pertinentes para provar o domínio sobre o tema que está se dispondo a palestrar.

**ps**: Acho que a pessoa pode mandar a candidatura para mais de um tema, mais só poderá palestrar sobre um, caso tenha sido a mais votada em mais de um tema.

## 4. Votação dos palestrantes

Caso para o mesmo tema tenha mais de uma pessoa se candidatando, faremos a votação para escolher quem irá palestrar.

---

Acho que dessa forma fica o mais justo possível, e ajuda em vários aspectos, alinhando ao máximo a conferência com o interesse da comunidade, e dando mais chances de outras pessoas participarem.

**Comment by marcosbergamo** [comment]
+1 @ericdouglas
