### ISSUE TITLE
@suissa

### ISSUE THREAD

**Issue by expertboyXX** [nodebr/nodeconfbr#32]
@suissa

**Comment by alanhoff** [comment]
@suissa, sabe explicar o que ta acontecendo?

**Comment by marcosbergamo** [comment]
+1 @alanhoff

**Comment by suissa** [comment]
Acho que o pessoal não manja de Github mano!

Isso que no texto do meu Fb diz que é só comentar @suissa lá no link hahahhaha
Da próxima vez eu desenho

**Comment by alanhoff** [comment]
uahuehuhauue, fechando então.
