### ISSUE TITLE
Reunião 02-02-2015 - 2º Milestone 

### ISSUE THREAD

**Issue by marcosbergamo** [nodebr/nodeconfbr#33]
Salve Galera!

Como havíamos combinado na primeira Milestone, na próxima semana na segunda-feira iremos ter nossa 2º Reunião e a partir do decorrido dessa ultima Milestone  iremos avançar para conseguir realizar nossa primeira NodeConf aqui no Brasil!

Estão todos convidados!

=== editado ===

**Horario: 20h**
**Hangout - O link será postado 1h antes do Call**
https://plus.google.com/hangouts/_/gtzw3uzigrqrjpxfs6rjqjjghua

**Comment by IgorDePaula** [comment]
Hora/canal?

Em 26 de janeiro de 2015 14:09, Marcos Vinicius Bérgamo <
notifications@github.com> escreveu:

**Comment by marcosbergamo** [comment]
Atualizei @IgorDePaula . Obrigado =D

**Comment by IgorDePaula** [comment]
Show de bola.

**Comment by fernandoGuisso** [comment]
Vai ser só online?

**Comment by ericdouglas** [comment]
Sim @fernandoGuisso é online!

**Comment by alanhoff** [comment]
Pessoal, qual o horário? Seria legal ser lá pelas 20h, o que acham?


--
Alan Hoffmeister
https://twitter.com/alan_hoff
https://github.com/alanhoff
https://keybase.io/alanhoff

2015-01-28 6:42 GMT-02:00 Eric Douglas <notifications@github.com>:

**Comment by marcosbergamo** [comment]
@alanhoff eu havia colocado no primeiro post as 19h,mas se todos concordarem no problem ser as 20h

**Comment by alanhoff** [comment]
Ah nem vi, deixa 19h então :-)


--
Alan Hoffmeister
https://twitter.com/alan_hoff
https://github.com/alanhoff
https://keybase.io/alanhoff

2015-01-30 18:25 GMT-02:00 Marcos Vinicius Bérgamo <notifications@github.com

**Comment by alanhoff** [comment]
Pessoal, vamos reagendar para a próxima segunda as 20h? Realmente esqueci da reunião, não marquei na agenda :/

**Comment by jeanleonino** [comment]
Olha, porque não nesta quarta-feira?

**Comment by alanhoff** [comment]
Não posso na quarta, na real a minha semana toda ta ferrada

**Comment by jeanleonino** [comment]
Segunda que vem que seja :)

**Comment by gustavodemari** [comment]
Galera, apenas 1 sugestão, porquê vocês não utilizam o agendamento do Hangouts para ter o link com mais antecedência? Acho que facilitaria bastante na divulgação.

Mais informações:
https://support.google.com/plus/answer/4386744?hl=en

**Comment by ericdouglas** [comment]
Pessoal, estava viajando e não consegui participar!

Segunda-feira está ok pra mim :+1:

**Comment by marcosbergamo** [comment]
Galera, tudo okey pra hoje? Pessoal dos Comitês?

@ericdouglas , @jeanleonino , @alanhoff , @willianjedai , @dalssoft , @heitortsergent , @gblmarquez

**Comment by alanhoff** [comment]
Tudo ok!

**Comment by realronchi** [comment]
Qual horário?

**Comment by marcosbergamo** [comment]
Parece que ficou marcado para as 20h =D

**Comment by gblmarquez** [comment]
confirmado!

**Comment by heitortsergent** [comment]
confirmado :hamburger:

**Comment by marcosbergamo** [comment]
Galera, alguém pode criar o link do Hangout e postar aqui e na lista? Tô pelo celular e dai vai ser meio tenso criar, se cair meu link cai de todos

**Comment by alanhoff** [comment]
Pessoal, to bem enrolado aqui, alguém consegue coordenar essa reunião?

**Comment by alanhoff** [comment]
@ericdouglas , @jeanleonino ,  @willianjedai , @dalssoft , @heitortsergent , @gblmarquez ?

**Comment by gblmarquez** [comment]
@alanhoff estou enrolado com um deploy...

**Comment by marcosbergamo** [comment]
Acho que vamos ter que remarcar novamente.

**Comment by dalssoft** [comment]
deploy nervoso aqui tb

On Mon, Feb 9, 2015 at 8:02 PM, Marcos Vinicius Bérgamo <
notifications@github.com> wrote:

> Acho que vamos ter que remarcar novamente.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodebr/nodeconfbr/issues/33#issuecomment-73599880>.
>



-- 
__________________

   David L. S.
dalssoft@gmail.com
__________________

**Comment by gblmarquez** [comment]
![image](https://cloud.githubusercontent.com/assets/367279/6116783/a13a057e-b096-11e4-9f63-38e887aece37.png)

**Comment by alanhoff** [comment]
Remarcar então!

**Comment by gblmarquez** [comment]
Próxima segunda?

**Comment by jeanleonino** [comment]
Valeu por remarcar, galera.

Jean.

**Comment by marcosbergamo** [comment]
Deal

**Comment by marcosbergamo** [comment]
Galerinha, sei que hoje é carnaval, mas como estamos para a reunião de hoje?

@alanhoff , @gblmarquez , @ericdouglas , @dalssoft , @jeanleonino , @willianjedai , @heitortsergent , @obetomuniz

**Comment by ericdouglas** [comment]
@marcosbergamo estou sem net em casa, hoje pra mim não vai ter como = (

**Comment by heitortsergent** [comment]
@marcosbergamo eu to disponível, mas acho melhor remarcarmos de qualquer jeito. O que discutirmos hoje pode ser completamente esquecido amanhã. :P

**Comment by marcosbergamo** [comment]
huehuehue por isso que vai estar sendo gravado =D

**Comment by marcosbergamo** [comment]
Galera, qual a melhor data para fazermos essa reunião? Lembrando que setembro já está logo ali!

**Comment by dalssoft** [comment]
Semana que vem?

2015-02-19 14:55 GMT-02:00 Marcos Vinicius Bérgamo <notifications@github.com
>:

> Galera, qual a melhor data para fazermos essa reunião? Lembrando que
> setembro já está logo ali!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodebr/nodeconfbr/issues/33#issuecomment-75090305>.
>



-- 
__________________

   David L. S.
dalssoft@gmail.com
__________________

**Comment by heitortsergent** [comment]
@marcosbergamo Segunda-feira dia 2 de Março? O que nós precisamos discutir na reunião?

**Comment by marcosbergamo** [comment]
Bom, acredito que o mais importante é analisarmos o que já foi feito até agora do que haviamos combinado e a partir daí botarmos o site já com o mínimo local, data e os horários. Abrir o call4paperz. Já tenho 3 confirmações de palestrantes internacionais, falta mais um que acho que seria legal discutirmos isso. 
A programação ficou bacana, só preciso corrigir algumas coisas que o @afucher comentou

**Comment by heitortsergent** [comment]
@marcosbergamo legal :D. Vamos esperar o pessoal falar então se dia 2 de Março tá ok.

**Comment by dalssoft** [comment]
Por mim fechou.

**Comment by ericdouglas** [comment]
@marcosbergamo :+1:

**Comment by marcosbergamo** [comment]
Galerinha!

É hoje, todos participaram?

**Comment by marcosbergamo** [comment]
Nota: Hoje as 20h ok??

@dalssoft , @alanhoff , @paulohp , @obetomuniz , @gblmarquez , @jeanleonino , @ericdouglas , @willianjedai

**Comment by paulohp** [comment]
Estarei presente!

**Comment by heitortsergent** [comment]
@marcosbergamo tem uma lista com email da galera? Mandar um convite do Google Calendar já com o link para o hangout

**Comment by alanhoff** [comment]
Estou criando a sala, 1 min

**Comment by alanhoff** [comment]
@dalssoft , @alanhoff , @paulohp , @obetomuniz , @gblmarquez , @jeanleonino , @ericdouglas , @willianjedai

https://plus.google.com/hangouts/_/gtzw3uzigrqrjpxfs6rjqjjghua

**Comment by alanhoff** [comment]
Vou fechar, não precisamos mais dela.

**Comment by dalssoft** [comment]
Sorry pessoal, não deu pra participar. Vou tentar aparecer na próxima.

**Comment by thebergamo** [comment]
Hi there,

Marcos Kefka's has invited you to Backend Brasil - SP.

Marcos Kefka's says:
----------------------------------------------------------------
Venha Conhecer o Backend Brasil - SP - Se você é desenvolvedor Backend ou quer vir a ser, esse é o seu lugar!
----------------------------------------------------------------

To find out more and join, click here:
http://www.meetup.com/Backend-Brasil-SP/t/if_137814002/?gj=ej4


If you're not interested, there's no need to do anything. Meetup will not keep your address on any list.
