### ISSUE TITLE
Pulseiras de Identificação

### ISSUE THREAD

**Issue by ericdouglas** [nodebr/nodeconfbr#34]
## Dúvidas:

1. Qual o tipo de pulseira vocês estão pensando para o evento?
1. Quantas unidades?
1. Cor?
1. O que vai ser escrito?

Após saber essas questões vou pedir os orçamentos e deixá-los aqui nessa issue.

## Orçar em

* http://www.automaticket.com.br/
* http://passevip.com.br/
* [mercado livre 1](http://produto.mercadolivre.com.br/MLB-616940393-kit-200-pulseiras-personalizadas-em-tyvex-_JM)
* http://www.printset.com.br/
* http://www.controlevip.com.br/
* http://www.ocprinter.com.br/
* http://www.ingressoideal.com.br/
* http://www.pulseiravirtual.com.br/
* http://www.printset.com.br/

**ps**: Se tiverem sugestões de mais locais para fazer orçamento, deixem o comment ai!

cc/ @dalssoft @alanhoff @marcosbergamo @willianjedai @paulohp @gblmarquez @heitortsergent

**Comment by marcosbergamo** [comment]
Interessante, achei que iriamos usar apenas o sistema de self login do leão. Mas acho que na pulseira seria interessante ter nome, identidade e telefone

**Comment by ericdouglas** [comment]
@marcosbergamo verdade cara, essa thread do sistema de self login rolou depois e eu acabei me esquecendo!

Talvez não precise mesmo, temos que ver como vai ficar isso!

Obrigado por lembrar!

**Comment by marcosbergamo** [comment]
=D

Mas acho bacana ter uma pulseira, acho que seria um pouco mais ecológico hehe.

**Comment by fernandoGuisso** [comment]
Legal essa da pulseira, mas o self login imprime uma etiqueta para colocar
no cracha, sera que é necessario essa pulseira? Ou melhor a pulseira sem o
cracha? Os dois eu acho mt coisa

**Comment by marcosbergamo** [comment]
Então eu tb acho mta coisa. Preferiria um ou outro tb

**Comment by gblmarquez** [comment]
o que acham de neste evento mantermos o mais simples possivel? assim podemos focar em melhorar a grade de conteudos.

**Comment by jeanleonino** [comment]
+1 para o mais simples. Gosto muito como foi feito o DevFest SP, foi só o self checkin. E até o lanche foi algo mais simples.

**Comment by IgorDePaula** [comment]
+1 simples

2015-01-29 16:17 GMT-02:00 Jean <notifications@github.com>:

**Comment by fernandoGuisso** [comment]
Pode ser só pulseiras, de PVC ou Vinil(a mais barata, não sei qual é) com um espaço mais largo pra gente colar as etiquetas que saem no self checkin.
O que acham?

**Comment by jeanleonino** [comment]
Que tal sem pulseira?

Jean.
Em 29/01/2015 19:57, "Luís Fernando Guisso Filho" <notifications@github.com>
escreveu:

**Comment by alanhoff** [comment]
Alguém tem uma impressora térmica e um rolo de adesivos pra me emprestar?
Faço o sistema de identificação e impressão com uma rasp + node.js depois
abro o código.

O adesivo colamos na camiseta e pronto :-)


--
Alan Hoffmeister
https://twitter.com/alan_hoff
https://github.com/alanhoff
https://keybase.io/alanhoff

2015-01-29 20:02 GMT-02:00 Jean <notifications@github.com>:

**Comment by jeanleonino** [comment]
@alanhoff o Luis Leão usou já um sistema open source. Com checkout usando
qr code até :)

Jean.
Em 29/01/2015 20:21, "Alan Hoffmeister" <notifications@github.com> escreveu:

**Comment by alanhoff** [comment]
Opa, só precisamos da impressora então?


--
Alan Hoffmeister
https://twitter.com/alan_hoff
https://github.com/alanhoff
https://keybase.io/alanhoff

Em 29 de janeiro de 2015 20:28, Jean <notifications@github.com> escreveu:

**Comment by jeanleonino** [comment]
Exato. No repositório tem os modelos indicados. Custa +- 250 reais. :) já
pego o repositório

Jean.
Em 29/01/2015 20:29, "Alan Hoffmeister" <notifications@github.com> escreveu:

**Comment by jeanleonino** [comment]
http://github.com/luisleao/self-checkin

Jean.
Em 29/01/2015 20:34, "Jean Lucas Monteiro Lima" <jeanleonino@gmail.com>
escreveu:

**Comment by alanhoff** [comment]
Ninguém tem uma pra emprestar não? Talvez podemos fazer uma vaquinha pra
comprar uma e deixar pra comunidade...


--
Alan Hoffmeister
https://twitter.com/alan_hoff
https://github.com/alanhoff
https://keybase.io/alanhoff

Em 29 de janeiro de 2015 20:41, Jean <notifications@github.com> escreveu:

**Comment by fernandoGuisso** [comment]
Só a etiqueta na camisa, bem pensado!

**Comment by alanhoff** [comment]
É, na real acho que tudo que precisamos é imprimir uma etiqueta com algumas
infos do cara pra ele não precisar ficar se apresentando pra todo mundo.


--
Alan Hoffmeister
https://twitter.com/alan_hoff
https://github.com/alanhoff
https://keybase.io/alanhoff

2015-01-29 21:22 GMT-02:00 Luís Fernando Guisso Filho <
notifications@github.com>:

**Comment by jeanleonino** [comment]
Sim, a impressora já imprime certinho. Eu topo a vaquinha se ninguém quiser. 50% do valor.

**Comment by fernandoGuisso** [comment]
Eu to querendo comprar uma, mas caso não aconteça eu topo vaquinha também.

**Comment by marcosbergamo** [comment]
Opá!  Se não me engano o pessoal do eventick empresta, já vi dessas no devbeers. Posso dar uma verificada. Mas se pá, vaquinha neles
