### ISSUE TITLE
Crowdfounding do evento

### ISSUE THREAD

**Issue by alanhoff** [nodebr/nodeconfbr#36]
Pessoal, na reunião de hoje pensamos em fazer um crowdfounding para levantar um dinheiro para o evento, qual a opinião de vocês?

**Comment by dalssoft** [comment]
Benchmark: CryptoRave
Email recebido hoje: https://gist.github.com/dalssoft/d97673bd5fdaea094159
Catarse: https://www.catarse.me/pt/cryptorave2015

**Comment by jeanleonino** [comment]
@dalssoft top!

**Comment by dalssoft** [comment]
A única diferença que eu vi da proposta deles em relação ao que discutimos é que a recompensa deles não é o ingresso, pois o CryptoRave é gratuito.

**Comment by fernandoGuisso** [comment]
Acho legal, ai os ingressos já são colocados como recompensa maior, para doações menores que o valor do ingresso podemos arrumar alguns livros ou mini palestras online que alguém se proponha a fazer para ajudar o evento.
Agora para patrocinadores tb poderia ser, mas com recompensas diferentes.

**Comment by dalssoft** [comment]
Parece que o pessoal está tendo dificuldade: conseguiram 18K de 30K
https://www.catarse.me/pt/cryptorave2015

**Comment by jeanleonino** [comment]
Esse é o tópico oficial sobre Crowdfunding?

Eu não acho legal colocar tudo pra crowdfunding, e depende de uma
divulgação anterior. E até uma estratégia de mídia para ele ser eficiente.
Só definir uma meta e jogar o projeto lá cria muitas chances de não
conseguir a grana, vários projetos morrem sem conseguir por causa disso
(mesmo sendo projetos bons).

Jean.

On 15 April 2015 at 14:05, David Lojudice Sobrinho <notifications@github.com

**Comment by dalssoft** [comment]
Eles conseguiram! https://www.catarse.me/pt/cryptorave2015
Dá pra ver que os slots de R$500 e R$1 mil tiveram um número razoável de doações.

**Comment by dalssoft** [comment]
@jeanleonino acho que vale pensar no crowdfunding como meio de divulgação, mas não somente. Com certeza podemos fazer outras coisas pra divulgar o evento antes de criar a campanha no catarse.

**Comment by thebergamo** [comment]
Não querendo ser chato, mas precisávamos resolver isso essa semana, se não bye bye NodeConfBR esse ano

**Comment by dalssoft** [comment]
+1

**Comment by jeanleonino** [comment]
Fechando essa issue, a discussão de crowdfunding via ficar em #47
