### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by jeanleonino** [nodebr/nodeconfbr#37]
Passos para a landing page (favor contribuírem): 

- [x] Endereço
- [x] Entrega do logo
- [x] Mailchimp (@alanhoff)
- [x] Boilerplate conferência
- [x] Design do site
- [x] Server
- [ ] Entrega do HTML
- [ ] Mídias sociais atualizadas

**Comment by jeanleonino** [comment]
Design da página, feito por @estudio86, parabéns pelo trabalho! 

![imgo](https://cloud.githubusercontent.com/assets/1311402/6485222/e65310a2-c260-11e4-98b8-7050f1dfc61c.jpg)

**Comment by jeanleonino** [comment]
Lembrando: os dados são de exemplo e textos serão escritos ainda pela parte de Publicidade e Propaganda, quem quiser ajudar é só mandar mensagem.

**Comment by estudio86** [comment]
Valeu @jeanleonino! =D

**Comment by alanhoff** [comment]
Pessoal, configurei um container para servir a pasta [landing][0] como arquivos estáticos, então qualquer commit para aquela pasta vai entrar no ar em http://conf.nodebr.org dentro de poucos segundos.

[0]: https://github.com/nodebr/nodeconfbr/tree/master/landing

**Comment by jeanleonino** [comment]
Perfeito, @alanhoff, tendo o HTML vamos fazer update no repositório aqui.

**Comment by joridos** [comment]
@jeanleonino tem o PSD do layout? posso estar dando uma força no front

**Comment by vitortalaia** [comment]
@jeanleonino @joridos Qualquer coisa eu posso ajudar também com o desenvolvimento

**Comment by joridos** [comment]
Pode crê @vitortalaia, quanto + gente ajudando melhor não?!

**Comment by vitortalaia** [comment]
:+1:

**Comment by jeanleonino** [comment]
@vitortalaia e @joridos, muito obrigado pela ajuda. A @estudio86, que fez o layout, começou a fazer o html e css no mesmo dia que entregaram o psd :) creio que se eles precisarem de ajuda irão avisar.

**Comment by joridos** [comment]
Entendi @jeanleonino, não tinha me ligado que era uma empresa que estava por traz

**Comment by jeanleonino** [comment]
A @estudio86 é um estúdio de design :)

**Comment by vitortalaia** [comment]
@jeanleonino @joridos Também não havia percebido... hahahaha

**Comment by estudio86** [comment]
Fala pessoal, tudo bem? Galera, seguinte. Agradeço demais por vocês oferecerem para ajudar com o HTML.

Eu havia me comprometido com o @jeanleonino de fazer aqui pela agência, mas, essa semana entrou um job monstro com prazo para ontem, então, por alguns dias não vou conseguir que o Front daqui trabalhe na Landing Page.

Queria saber se teria problema passar o PSD para algum de vocês que se propôs a ajudar (@joridos ou @vitortalaia). Algum de vocês consegue quebrar esse galhão para nós?

O que acha @jeanleonino, teria algum problema fazermos dessa forma?

Abraços e boa noite (ou madrugada de trabalho haha)

**Comment by joridos** [comment]
Por min ta suave manow, precisando estamos ai!

**Comment by vitortalaia** [comment]
Por mim, ok.

**Comment by jeanleonino** [comment]
@estudio86 por mim suave, você que manda. Se mandar o PSD pra mim eu coloco no github depois. Ou o @alanhoff, @marcosbergamo podem fazer.

**Comment by vitortalaia** [comment]
@jeanleonino Por mim tudo bem, e aí @joridos?

**Comment by joridos** [comment]
Tranquilo @vitortalaia !

**Comment by IgorDePaula** [comment]
Eu tb possodar uma força no front.

**Comment by IAMFELIPESOUZA** [comment]
opa! me envolve no front também rs.

**Comment by fernandoGuisso** [comment]
Só pra saber, já ta dando andamento na coisa?

**Comment by vitortalaia** [comment]
@fernandoGuisso Ainda não, pelo que eu sei...

**Comment by joridos** [comment]
@fernandoGuisso @vitortalaia @jeanleonino ainda ninguem postou o **PSD**

**Comment by IAMFELIPESOUZA** [comment]
a org usa algum meio de comunicação, como gitter ou slack?

**Comment by fernandoGuisso** [comment]
Gitter https://gitter.im/nodebr/nodeconfbr
Sera que precisa do PSD pra começar, pq tb se usar SVG nesses bg vai ter que fazer o vetor no Illustrator.

**Comment by IAMFELIPESOUZA** [comment]
se for seguir esse prototipo da pra fazer o skeleton no olho fácil fácil.

**Comment by fernandoGuisso** [comment]
@estudio86 to tentando otimizar o SVG, se puder falar comigo depois, vlw

**Comment by estudio86** [comment]
Opa, bom dia @fernandoGuisso. O que manda?

**Comment by IAMFELIPESOUZA** [comment]
@estudio86, disponibiliza o psd pra gente!

**Comment by fernandoGuisso** [comment]
@estudio86 eu preciso do arquivo .Ai com as letras antes de expandir a aparência, se puder entra pelo gitter pra ficar melhor de conversar

**Comment by estudio86** [comment]
Eu tinha enviado já para o @jeanleonino, posso jogar aqui mesmo o arquivo?

Eu não entendo nada de Git, então, se puder enviar por aqui é mais fácil:
https://www.dropbox.com/s/45gwqv26c61duxg/landing-page-nodeconfbr-3.psd?dl=0

**Comment by estudio86** [comment]
@fernandoGuisso Cara, não tenho arquivo em .AI, o layout foi todo feito no PS

**Comment by fernandoGuisso** [comment]
@estudio86 to falando do logo, foi feito no illustrator né?

**Comment by IAMFELIPESOUZA** [comment]
@alanhoff @paulohp @thebergamo deem uma olhada na [landing page](https://github.com/IAMFELIPESOUZA/landing-nodeconf-br)

**Comment by neysimoes** [comment]
Vou revisar o código da LP com o @IAMFELIPESOUZA acho que algumas coisas podem ser melhoradas. Acho que o @gpedro vai mandar um PR também. (:

**Comment by gpedro** [comment]
to mandando o PR agora. ((:

**Comment by thebergamo** [comment]
@gpedro pode mandar o PR... @IAMFELIPESOUZA estou vendo a landing!

**Comment by gpedro** [comment]
@thebergamo já mandei PR com o workflow atualizado e com mais javascript 0/ Agora é @neysimoes e @IAMFELIPESOUZA mandar bala ((:

**Comment by neysimoes** [comment]
@thebergamo conversei com o @gpedro e ele adicionou algumas coisas no workflow que vamos usar para deixar a LP bala! Hoje eu já pego essa demanda, vou conversar com o @IAMFELIPESOUZA para ver se ele pode ver comigo hoje se não depois eu alinho com ele.

**Comment by thebergamo** [comment]
Perfeito galera =D 
Não consegui rodar a página, os comandados lá no readme.md não funcionam, qdo fui ver o package.json acho que está quebrado

**Comment by gpedro** [comment]
@thebergamo tá "quebrado" por conta do main.styl

**Comment by thebergamo** [comment]
blzinha =D

Qualquer ajuda que precisem só mandar um alô!

**Comment by gpedro** [comment]
@thebergamo mandei outro PR corrigindo o build :P

**Comment by jeanleonino** [comment]
@thebergamo você pode ficar à cargo dessa issue?

**Comment by thebergamo** [comment]
Tomarei conta então. Vou conferir os avanços de hoje =D

**Comment by thebergamo** [comment]
Pessoal eu abri a landing aqui.. vi algumas coisas estranhas.(dei pull hoje as 9:45) 
Na lateral tem uma lista de navegação entre as partes do site. Vi também que ainda não está responsivo é isso mesmo?

Entretanto, caras estão de parabéns @IAMFELIPESOUZA , @gpedro e @neysimoes tá ficando bem bacana isso tudo! Vocês são d+

**Comment by thebergamo** [comment]
some news here?

**Comment by gpedro** [comment]
@thebergamo acabei de reescrever quase todo layout usando Stylus, Jeet e Rupture. Aproveitei pra melhorar a nomenclatura das classes até para poder colocar alguns schemas, melhorar em SEO e incrementar um pouco mais de acessibilidade.

> https://github.com/gpedro/landing-nodeconf-br

depois o @neysimoes vai dar um tapa na macaca da responsividade. @IAMFELIPESOUZA deixei algumas coisinhas faltando lá, se puder contribuir no meu fork, agradeço. Assim que finalizar eu mando pro **upstream**.

**Comment by thebergamo** [comment]
Beleza a noite eu dou uma testada. Estava querendo fechar isso até o final da semana acha possível? @gpedro

**Comment by gpedro** [comment]
@thebergamo é possível fechar até final de semana sim :) já tá na reta final

**Comment by gpedro** [comment]
galero, subi um gh-pages pra dizerem no que melhorar e etc.

http://gpedro.github.io/nodeconfbr/

Qualquer coisa, só mandar um PR
http://github.com/gpedro/nodeconfbr

**Comment by IgorDePaula** [comment]
Rapaz,ta muito bom sôr...

2015-04-28 16:22 GMT-03:00 Gabriel Pedro <notifications@github.com>:

**Comment by gpedro** [comment]
@thebergamo 
> tipo os botôes ser vazados em todos os casos se não perde um pouco da identidade visual

mudei lá, fica melhor tudo vazado ou não?
http://gpedro.github.io/nodeconfbr/

**Comment by IAMFELIPESOUZA** [comment]
deixa comigo essas issues aí hein ewoiewowe

**Comment by gpedro** [comment]
@thebergamo dá uma olhada

**Comment by gpedro** [comment]
@estudio86 poderia fazer um favicon e uma imagem pro OpenGraph para nós ? :P

**Comment by thebergamo** [comment]
blzinha galera =D

Vou cobrar isso na sexta hein e quero abrir no meu celular o site bonitão =D segunda feira seria fantastico se já estivessemos com tudo pronto para iniciar a campanha!

**Comment by gpedro** [comment]
site no celular já tá lindão: gpedro.github.io/nodeconfbr. Só falta algumas ajustes básicos e o fucking menu. Estou pensando ainda como irei fazer esse menu flutuante. Pra PC, tudo bem, mas pra mobile/tablet... não sei se tiro ele no mobile/tablet ou coloco um menu escondido no canto, dai clica que abre.

**Comment by thebergamo** [comment]
Cara, celular acho que podia botar ele como um botão contraido na lateral, será que dá?

**Comment by gpedro** [comment]
sim sim, dai clica no botão contraido na lateral e ele sobe pra tela o menu igual é no pc?

**Comment by gpedro** [comment]
@thebergamo encontrei [este layout](http://estudio86.com.br/clientes15/nodeconfbr/img/home.jpg) em uma das issues, devo trabalhar em cima dela também? Acredito que agora só vai faltar o Menu

**Comment by gpedro** [comment]
@thebergamo @alanhoff @estudio86  ping

**Comment by thebergamo** [comment]
@gpedro verdade faz total sentido...preciso pedir uma ajuda pro estudio86. Tento ver com ele e te mandar a noite. Não consegue adicionar a seção e seguir o padrão?

Ai os fundos e afins a gente vai fazendo depois.

**Comment by estudio86** [comment]
@thebergamo @gpedro Não entendi, você precisa do PSD da Landing Page?

Então, o layout não tem agenda nem palestrantes por que quando finalizei ele, essas informações não existiam. Se já tiver os dados, me manda que monto algo por aqui.

**Comment by gpedro** [comment]
@estudio86 pode colocar dados fictícios mesmo.
> http://braziljs.github.io/conf-boilerplate/#speakers

**Comment by estudio86** [comment]
@gpedro Então, mas precisa saber quais infos de cada coisa precisam estar no layout. Tem algum link de referência para eu ver?

**Comment by gpedro** [comment]
@estudio86 
refs:
http://conferenciacssbrasil.com.br/
http://frontincuiaba.com.br/
http://frontinfloripa.com.br/

**Comment by thebergamo** [comment]
@gpedro acho que isso dai resolve =D

**Comment by gpedro** [comment]
@alanhoff @thebergamo @neysimoes @IAMFELIPESOUZA 
o que vocês acham desse conceito inicial para os palestrantes?

**Comment by estudio86** [comment]
Fala pessoal, bom dia. Achei legal esse modelo que o @gpedro montou. Montei mais 1 opção aqui também:

![palestrantes](https://cloud.githubusercontent.com/assets/5941705/7512333/a3f4bb44-f482-11e4-9822-2d99d418ea3e.jpg)

Ou assim, com um mini currículo de cada palestrante:

![palestrantes-2](https://cloud.githubusercontent.com/assets/5941705/7512464/8a5176f4-f483-11e4-8fcd-f156e78305bb.jpg)

**Comment by thebergamo** [comment]
+1 pra com mini bio...

**Comment by jeanleonino** [comment]
+1 pra com mini bio.

**Comment by joridos** [comment]
:+1:  com mini bio.

**Comment by IAMFELIPESOUZA** [comment]
+1 mini bio

**Comment by joridos** [comment]
Legal seria ter uma seção **Programação**.
Como em [conferenciacssbrasil](http://conferenciacssbrasil.com.br/).
![Imgur](http://i.imgur.com/LNMCodG.png?1)

**Comment by estudio86** [comment]
Então, acho legal ter sim, mas, nesse site ai tem os dois, a área palestrantes e a agenda separadas.

**Comment by gpedro** [comment]
@estudio86 muito bom, mas serão ~12 palestrantes, separando de dois em dois com mini-bio vai ficar muito extenso. Não consegue pensar em algo mais comprimido?

**Comment by talyssonoc** [comment]
(Espero não estar caindo muito de paraquedas na discussão)

@gpedro @estudio86 Não rola fazer a bio substituir a foto quando se coloca o mouse sobre a mesma ? Como se a foto "rodasse" e estivesse escrito atrás, algo assim, aí cria barra de rolagem dentro da caixa caso o texto não couber (talvez isso implique que deva aumentar um pouco o tamanho da foto pra não ficar muito pequeno o espaço pro texto).

**Comment by gpedro** [comment]
@talyssonoc estamos pensado em algo parecido. Seria como um lightbox. Scrollar :-1:.
obrigado pela sugestão. Temos algumas [issues](https://github.com/IAMFELIPESOUZA/landing-nodeconf-br/issues) para serem resolvidas, se puder contribuir, agradecemos.

**Comment by estudio86** [comment]
@gpedro @talyssonoc Acho que rola sim, ou ainda, um hover. Quando passar o mouse sobre a foto, ele exibir o texto da mini bio e os ícones sociais. Estou fora, mas, chegando, monto um layout e mando aqui, tudo bem?

**Comment by gpedro** [comment]
@talyssonoc http://www.frontinfortaleza.com.br/#speakers

**Comment by talyssonoc** [comment]
Foi mais ou menos assim que tinha pensado mesmo, @gpedro

**Comment by thebergamo** [comment]
@gpedro É isso ai cara.. acho que vai ser massa!

**Comment by thebergamo** [comment]
@gpedro como estamos? Precisa de algum help?

Já temos uma quantidade fixa de speakers. Se quiser já te passo.

Queria muito lançar o site junto com o C4P!

Acha que rolar trocarmos uma ideia hoje a noite pra finalizarmos o que falta? Eu te ajudo se for o caso.

**Comment by gpedro** [comment]
@thebergamo estamos aqui. Estou aguardando que o @IAMFELIPESOUZA ficou de fazer. As outras coisas irei retomar hoje.
