### ISSUE TITLE
Reunião dia 09/03/2015

### ISSUE THREAD

**Issue by alanhoff** [nodebr/nodeconfbr#38]
Pessoal, por favor confirmar a presença na próxima reunião.

https://plus.google.com/u/0/events/cke5r7n76820plu5qh6dd10rs9c

@dalssoft, @alanhoff, @paulohp, @obetomuniz, @gblmarquez, @jeanleonino, @ericdouglas, @willianjedai

**Comment by ericdouglas** [comment]
@alanhoff :+1:

**Comment by dalssoft** [comment]
Ok. Qual horário?

**Comment by alanhoff** [comment]
20h como a última :-)

**Comment by marcosbergamo** [comment]
Salve galera =D

Todos confirmados?

**Comment by alanhoff** [comment]
Yes!

**Comment by jeanleonino** [comment]
:+1:

**Comment by dalssoft** [comment]
confirmado

On Mon, Mar 9, 2015 at 2:15 PM, Jean Lucas <notifications@github.com> wrote:

> [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nodebr/nodeconfbr/issues/38#issuecomment-77898424>.
>



-- 
__________________

   David L. S.
dalssoft@gmail.com
__________________

**Comment by dalssoft** [comment]
e ai? vai rolar?
