### ISSUE TITLE
Local do Evento

### ISSUE THREAD

**Issue by jeanleonino** [nodebr/nodeconfbr#40]
Precisamos urgentemente fechar um local para o evento que suporte as seguintes condições: 

- Suportar 200 pessoas no mínimo; 
- Ter infraestrutura de TI; 
- Ter infraestrutura básica (banheiros, saídas de emergência, etc); 

Nessa ordem. :-)

**Comment by jeanleonino** [comment]
Eae pessoal, novidades nesse ponto? Quais são as opções? O que tem travado cada um?

**Comment by willianjedai** [comment]
Então, eu e o @marcosbergamo pedimos um orçamento para o Centro de Convenções Rebouças, onde aconteceu o GDG Fest aqui em SP.

Eles possuem um auditório para 200 lugares:

**AUDITÓRIO AMARELO (200 lugares)**
*- das 8:00 às 18:00 horas: R$ 4.759,83*
*- das 19:00 às 24:00 horas: R$ 2.977,82*
*- das 8:00 às 24:00 horas: R$ 5.488,39*

E um Salão de exposição, caso haja os monitores espalhados e um espaço de descontração e networking:
**Tamanho**: 270m²
**Capacidade para recepção**: 270 participantes
**Capacidade para banquete**: 220 participantes
*- das 8:00 às 18:00 horas: R$ 3.174,57*
*- das 8:00 às 24:00 horas: R$ 3.934,03*

**Outras infos:**
*Caso tenha exposição/feira será necessário a locação do Salão de Exposição e/ou Salão Nobre um dia anterior para a montagem, no horário das 08:00 às 24:00 horas.*

*Disponibilizaremos como cortesia:*
- *Mobiliário para montagem da Secretaria (mesas com balconetes, mesas retangulares, sofás, poltronas, armários)*
- *Bandeiras / Púlpito / Lousa / Placas de Sinalização / Pedestais para Banner / Unifilas / Flip Charter (sem papel)*
- *Ramal telefônico somente para secretaria do evento (Ligações DDD + DDI + Utilizações, serão cobradas a parte)*

*FORMA DE PAGAMENTO: Na confirmação da reserva, será necessário entrada de 20% do valor total. O restante poderá ser parcelado, sendo que o valor total deverá estar quitado até 10 dias antes do evento.*

Neste caso, pelo que vi do auditório amarelo, nem telão possui. Então teríamos o gasto com isso também. 

Estou com infos do auditório do Scup, só que não achei muito vantajoso.

O espaço é para 140 cadeiras, e não tem funcionamento de rede 3g/4g e nem pontos de rede no local. Então, acho que para este evento não seria tão bom, mesmo que seja barato o espaço.

Também entrei em contato com o @aleborba sobre o espaço do google, e ele me informou que o Google só cede espaço para eventos gratuitos, então, não há uma possibilidade de promover o evento lá.

O @marcosbergamo está vendo um local com a faculdade Anhembi Morumbi senão me engano, e em breve deve ter mais informações.

Por enquanto é isso, vou tentar saber mais sobre o auditório da telefônica essa semana, que o @heitortsergent tinha comentado na primeira reunião, mas em todo caso, precisamos achar mais lugares viáveis para ter mais opções, vou tentar conversar com alguma galera que já tenha feito eventos grandes para ter mais sugestões.

**Comment by heitortsergent** [comment]
@willianjedai vou te apresentar para o pessoal da Telefonica por email

**Comment by marcosbergamo** [comment]
se puder me coloca em cópia @heitortsergent

**Comment by marcosbergamo** [comment]
Galera, 

seguem 2 lugares que eu cotei:

**TEATRO FREI CANECA**
``` 
Setembro

03 (5ªf) – das 08h às 18h com desmontagem até às 19h

04 (6ªf) – das 08h às 18h com desmontagem até às 19h

07 (2ªf) – das 08h às 22h

08 (3ªf) – das 08h às 18h com desmontagem até às 19h

 

O Teatro oferece:

 

Equipe de limpeza

02 (dois) técnicos de apoio

Foyer - 7° andar

Auditório com capacidade para 600 pessoas – 7° andar

 

O valor da diária é de R$ 20.000,00 (vinte mil reais)

O valor com desconto para as 02 (duas) diárias será de R$ 28.000,00 (vinte e oito mil reais)

 

O estacionamento é negociado diretamente com a ESTAPAR (11) 3472-2113

 

Equipamentos de sonorização e projeção:

01 tela Nardelli Mapa Luxo 200’’

01 projetor de 1800 ansi-lumens

03 microfones

02 caixas de som (somente na platéia)

01 CD player

01 DVD player

01 geral de lâmpadas pares para o procênio.
```

**Maksoud Plaza**

```
TEATRO MAKSOUD Anfiteatro 
05/09/2015 08:00 à 06/09/2015 18:00  
Capacidade 400 
Valor diária: 16.300,00
Total (R$) 32.600,00

Equipamentos e afins devem ser negociados a parte.
```

O que acham??

**Comment by marcosbergamo** [comment]
@jeanleonino planilha: https://docs.google.com/spreadsheets/d/1RHOZXDJiSQcXJvA2VhVGLgOUgh2wto6dfsDudmun5Mg/edit?usp=sharing

**Comment by heitortsergent** [comment]
@marcosbergamo qual seu email? Não vai dar pra fazer na Telefonica :(

**Comment by marcosbergamo** [comment]
@heitortsergent  te mandei no wpp

**Comment by thebergamo** [comment]
Pessoal, acabei de receber a confirmação de que poderemos fazer no IBTA. Precisamos ver certinho como vamos proceder, pois lá não tem auditório, mas podemos usar as salas de aula. E usar 2 Andares. 
Quem quiser vir comigo na segunda ou terça pra vermos os locais para usarmos só dar um toque.

**Comment by ericdouglas** [comment]
Boa @thebergamo ! :smile:

**Comment by thebergamo** [comment]
Vamos ter que mudar o formato... mas vai funcionar hehe

**Comment by fernandoGuisso** [comment]
Só pra saber, vai ser free?

**Comment by thebergamo** [comment]
Galera, vou no IBTA hoje a noite ver as salas. Alguem pode me acompanhar? @willianjedai, @fernandoGuisso

**Comment by fernandoGuisso** [comment]
Mano, to na FIESP, na hora q acabar a reunião aqui eu até vou, pode ser?

**Comment by thebergamo** [comment]
Deixei pra outro dia, acabei perdendo o tempo.

**Comment by fernandoGuisso** [comment]
To aqui, quer q espere? Ou que vá lá?

**Comment by jeanleonino** [comment]
Updates aqui? Pode fechar?

**Comment by brunobelarmino** [comment]
Pessoal, sou o Bruno e estou chegando agora aqui no github do nodeconf Brasil e com muita vontade de contribuir.

Vocês já conguiram fechar o local do evento?
Caso não, o evento precisa ser na cidade de São Paulo? Pois sou de Campinas a 1h de SP e estava pensando na Unicamp aqui. Poderia tentar ver se rola, o que acham?

**Comment by thebergamo** [comment]
Fala @brunobelarmino  tudo bem?

Já estamos com alguns lugares em mente =D

Na próxima segunda feira teremos uma reunião se quiser participar =D

**Comment by brunobelarmino** [comment]
@thebergamo show de bola!
Gostaria de participar da reunião sim. Você pode me passar o endereço de onde vai ser e o horário?

**Comment by thebergamo** [comment]
Vamos fazer via hangouts.. normalmente ocorre as 19h da segunda feira. Acredito que divulgaremos o link aqui perto do horario.

**Comment by dalssoft** [comment]
https://plus.google.com/u/0/events/c96va5i47gl83b8peb8koojaqgo/108345064538342886853

**Comment by candreva** [comment]
Fala pessoal, indicação do @guisouza, estou aqui pra ajudar.

Já organizei tudo quanto é evento, inclusive recentemente muitos startup weekends.

Todos os espaços que vocês estão vendo são pagos?

Qual a data e horário do evento?

**Comment by candreva** [comment]
Tenho algumas opções interessantes de espaços gratuitos, e outros quase sem custo.

Preciso entender o formato e ter mais detalhes do evento.

Como esta a questão de patrocínios?

**Comment by guisouza** [comment]
@candreva muito provavelmente 7 e 8 de novembro
quanto a horários ou formatos, vamos ser flexíveis de acordo com o local que a gente conseguir .. 
a idéia inicial, é que consigamos nos bancar sem patrocínios, um evento da comunidade,
para a comunidade, bancado pela comunidade. 
por isso o catarse

**Comment by candreva** [comment]
Entendi... 

Ter um mídiakit é uma parada legal para caso surja ou passam surgir empresas interessadas e não queiram ir pelo catarse.

Preciso de mais infos acerca do espaço e do que vcs enxergam como necessidades reais do evento.

Número de participantes, auditório (s ou n), recepção, espaço pra alimentação, horário ideal, de que horas a que horas, pra qual público, qual objetivo e etc....

Talvez consigo até um apoio da Prefeitura, estou com ótimo relacionamento com a SP negócios e eles podem eventualmente ceder um espaço fudido.... fizemos um no Centro Cultural de SP foi foda!!

**Comment by guisouza** [comment]
@candreva, como eu disse, o formato do evento vai se basear no local que conseguirmos. 
dá uma olhada no documento anexo a issue #51 

Seria interessante se conseguíssemos tocar o evento sem nenhuma empresa agora que partimos para o catarse, mas creio que estamos abertos a propostas, discutimos isso na issue #5

**Comment by thebergamo** [comment]
No momento já temos a Faculdade Rio Branco que cedeu o espaço pra gente =D
