### ISSUE TITLE
Pauta Reunião 06/04/2015

### ISSUE THREAD

**Issue by thebergamo** [nodebr/nodeconfbr#45]
Presentes: @thebergamo, @dalsoft, @ericdouglas

Nessa reunião falamos sobre o local e os próximos passos que deveríamos abordar para a realização da conf na data prevista. 

*Próximos passos*
* Modelar e Definir melhor a abordagem do crowdfunding (e.g metas e cenários) 
* Definir os atrativos para patrocinadores 
* Botar a landing page no ar visando que já temos um local definido. 
* Reunião dos coordenadores responsáveis que moram em SP fisicamente ou outros que moram fora via Hangout o mais rápido possível. (Possivelmente na quinta??) 

(irei citar os que estão em sp embaixo) 
@gblmarques, @alanhoff, @heitorburger, @wilianjedai, @studio86

O restante estão todos convidados a participar remotamente via Hangout. Se não citei alguém peço desculpas e pode aparecer também!!

**Comment by thebergamo** [comment]
@gblmarques, @heitortsergent , @willianjedai, @alanhoff, @studio86 o que acham de fazermos a reunião amanhã? umas 19h???

**Comment by dalssoft** [comment]
@gblmarquez :)

**Comment by dalssoft** [comment]
@gblmarquez com Z no final e @dalssoft com dois SS rsrs

**Comment by dalssoft** [comment]
Por mim amanhã (09, quinta) pode ser. Se quiser marcar no Scup, tem sala disponível pra gente aqui.

**Comment by heitortsergent** [comment]
@thebergamo essa semana eu não consigo :(. Dependendo das outras pessoas, podemos marcar para o começo da semana que vem?

**Comment by thebergamo** [comment]
@alanhoff  e @gblmarquez o que acham?

**Comment by gblmarquez** [comment]
por mim pode ser qualquer dia, menos na sexta da próxima semana pois vou viajar

**Comment by thebergamo** [comment]
Vou marcar na próxima Terça-Feira(12/04) acho que vai ser uma data boa para todos não?

**Comment by willianjedai** [comment]
Acho terça que vem de boa. Só definirmos um horário mais cedo para eu adiantar as coisas e ir para reunião.

**Comment by heitortsergent** [comment]
:+1:

**Comment by thebergamo** [comment]
Pessoal, vou criar uma issue com o local.
