### ISSUE TITLE
Reunião Presencial 14/04/2015

### ISSUE THREAD

**Issue by thebergamo** [nodebr/nodeconfbr#46]
Pessoal, 

Conforme falamos, seguem os dados da reunião amanhã.

**Local:** - Pagar.me - Av. Brigadeiro Faria Lima, 1811. São Paulo - SP
**Horário:** - 19:30

@alanhoff , @dalssoft , @heitortsergent , @willianjedai , @ericdouglas , @gblmarquez

**Comment by ericdouglas** [comment]
Confirmado! :+1:

**Comment by dalssoft** [comment]
seria legal se o @jeanleonino pudesse participar via hangout

**Comment by thebergamo** [comment]
Alguém vai vir??

**Comment by dalssoft** [comment]
Cheguei. Com quem eu falo?

**Comment by willianjedai** [comment]
Estou saindo agora do Scup. Já chego ai.

**Comment by heitortsergent** [comment]
Foi mal, estávamos fazendo um release na empresa e esqueci completamente. :(

Desculpa mesmo, sei que estive ausente nas últimas reuniões.

**Comment by thebergamo** [comment]
Tenta colar aqui se não tiver longe...

**Comment by dalssoft** [comment]
Registro do evento: https://twitter.com/dalssoft/status/588142494740832256
:)

**Comment by fernandoGuisso** [comment]
O que rolou de bom ai?

**Comment by dalssoft** [comment]
@fernandoGuisso fechamos o planejamento da primeira meta do crowdfundind: https://github.com/nodebr/nodeconfbr/issues/47

**Comment by jeanleonino** [comment]
@dalssoft já fecharam as metas? Lá na issue de crowdfunding tá bem confuso.

**Comment by dalssoft** [comment]
@jeanleonino a ideia inicial está lá. Agora é ir ajustando...

Se tiver dúvidas, pode colocar lá.

**Comment by alanhoff** [comment]
Pessoal, tem alguma ata da reunião de ontem? Eu to vendo que foi decidido um monte de coisas mas o pessoal daqui não conseguiu opinar ainda.

**Comment by dalssoft** [comment]
@alanhoff Tentei fazer um resumo aqui: https://github.com/nodebr/nodeconfbr/issues/47#issuecomment-93858709

**Comment by alanhoff** [comment]
Show! Deu pra entender perfeitamente, bola pra frente agora! :-)


--
Alan Hoffmeister
https://twitter.com/alan_hoff
https://github.com/alanhoff
https://keybase.io/alanhoff

2015-04-16 20:03 GMT-03:00 David Lojudice Sobrinho <notifications@github.com

**Comment by heitortsergent** [comment]
valeu @dalssoft :+1:

**Comment by gblmarquez** [comment]
Pessoal atualizei a planilha com o orçamento que recebi, com valores reais. Aproveitei e pedi um orçamento de uma camiseta polo de qualidade para todos nós que estamos na organização.
https://docs.google.com/spreadsheets/d/18_3oHtJ4exOieBTM5FTUPnnbG_SDuNm0dofQW1jYG2E/edit?usp=sharing

@alanhoff @dalssoft @thebergamo @jeanleonino @fernandoGuisso @willianjedai @ericdouglas @heitortsergent @studio86

**Comment by ericdouglas** [comment]
@gblmarquez show :+1:

**Comment by dalssoft** [comment]
Gostei da ideia das camisetas. 

E achei caro demais as canecas. Se tirar o custo das canecas, dá pra fazer sem patrocinador, apenas cobrando R$150 para as 100 pessoas.

**Comment by ericdouglas** [comment]
@dalssoft verdade... pode deixar como algo adicional no Catarse.

**Comment by thebergamo** [comment]
Acho melhor deixar como meta também @ericdouglas talvez deixar uma opção "page 150 + 30 e ganhe a caneca"

O que acham de algo do tipo?

Acham que conseguimos sentar pra ver isso essa semana para lançar a campanha?

**Comment by ericdouglas** [comment]
@thebergamo o problema de deixar em aberto é que se apenas 30 pessoas quiserem, o valor unitário da caneca deve aumentar né...

Se conseguir pelo mesmo preço, ai com certeza é uma ótima opção.

**Comment by thebergamo** [comment]
Hum... ai temos que ver certinho com o @gblmarquez

**Comment by gblmarquez** [comment]
@thebergamo @ericdouglas vou levantar o preço para 30 canecas

**Comment by thebergamo** [comment]
Alguma novidade?
