### ISSUE TITLE
Planejamento Metas Crowdfunding

### ISSUE THREAD

**Issue by willianjedai** [nodebr/nodeconfbr#47]
Planejamento de metas crowdfunding para dois palestrantes estrangeiros com 100 participantes, coffeebreak e local subsidiado pelo IBTA.

Link: https://docs.google.com/spreadsheets/d/18_3oHtJ4exOieBTM5FTUPnnbG_SDuNm0dofQW1jYG2E/edit?usp=sharing

**Comment by dalssoft** [comment]
Pessoal, por favor, fazer um double check, mandar críticas e sugestões. Quando tiver legal, vamos criar a segunda e terceira meta do crowdfunding baseada nessa primeira.

**Comment by dalssoft** [comment]
Antes de falar o que foi decidido, tomamos como premissas que, sendo o nodeconfbr um evento feito 100% pela comunidade, o crowdfunding é a forma mais segura para garantir a realização do evento sem envolver riscos financeiros para nenhuma pessoa ou empresa.

Partimos também de custos levantados nas rodadas anteriores para montar uma planilha de custos inicial. A partir daí decidimos algumas coisas:

(1) Pensamos num formato de metas evolutivas. Ex:
Meta 1: 2 palestrantes internacionais, local do evento gratuito (100 pessoas)
Meta 2: 4 palestrantes internacionais, local do evento pago (250 pessoas)
Meta 3: etc.

As metas estão relacionadas diretamente com os custos do evento, que são basicamente duas: palestrante internacional e local.

(2) Slots para pessoas. Valor único (aprox. R$ 150). Recompensa: o ingresso e uma caneca do evento. Outros brindes durante o evento.

(3) Slots para empresas. Valor depende do tipo de slot. Recompensa: Garante espaço em banner e nome do coffeebreak.

(4) Separar as metas dos slots. Isso garante que independente do cenário (mais empresas ou mais pessoas patrocinarem), as metas possam ser atingidas.

(5) Brindes. Achamos que ter o mínimo de brindes é um atrativo para as pessoas e que faz a diferença. Achamos melhor deixá-los no custo do evento.

Criamos apenas a Meta 1. Se estiver tudo ok com essa meta, começamos a criar as outras.

Não se pensou o formato de divulgação do evento e onde o próprio crowdfunding entra nessa estratégia. Essas questões estão em aberto.

**Comment by dalssoft** [comment]
Perguntas foram feitas na própria planilha via comment. Estou respondendo algumas por lá mesmo.

**Comment by thebergamo** [comment]
Senhores, alguém pode me ajudar a montar o crowdfounding no catarse? @dalssoft, @alanhoff , @heitortsergent , @willianjedai , @paulohp , @gblmarques

**Comment by dalssoft** [comment]
Ajudo sim. Essa semana tá meio puxado aqui, mas dou um jeito.

Mas antes de montar, qual vai ser o plano de divulgação? 
E faremos antes? Faremos durante? 

@jeanleonino , ajuda a gente com isso?

**Comment by thebergamo** [comment]
@dalssoft acho que temos que divulgar nas redes sociais, talvez algumas campanhas no facebook acho que a campanha pode rolar paralelo.

Se o @studio86 pudesse fazer um banner para a gente postar na sexta feira com uma chamada pro Evento ia ser bem bacana.

@dalssoft acha que rola nos reunirmos sexta?

**Comment by thebergamo** [comment]
https://www.catarse.me/pt/nodeconfbr-2015

**Comment by dalssoft** [comment]
Boa. Infelizmente não vou estar por aqui na próxima semana. Só vou poder conversar depois do dia 11/05. :/

**Comment by thebergamo** [comment]
Putz... a gente precisava lançar isso até no máximo a próxima semana. :(

**Comment by jeanleonino** [comment]
E aí, pessoal, voltei, posso voltar a dar uma força nisso. O que tá havendo? Como tá o status? 

Vai ter só um slot de compra mesmo para pessoa física? Não pode comprar com CNPJ nessas plataformas de crowdfunding, não é? Como ficaria o de empresas no caso?

**Comment by jeanleonino** [comment]
Sinceramente, a estratégia do crowdfunding com os brindes é que pessoas que não possam "pagar pelo prêmio" ainda peguem algo... 

Pelo que entendi da thread da reunião presencial, mas que não está aqui, dá para ter quatro slots no mínimo: 

* Brinde caneca (5 vagas)
* Ingresso (75?)
* Ingresso + brindes (25)

Acho que assim você otimiza muito mais, quem quer só doar para ajudar a campanha sair, pode doar canecas.

**Comment by jeanleonino** [comment]
Agora um **problema**: realmente vai valer a pena vender todos os ingressos agora, não é melhorar segurar alguns para vender depois? Porque no fim das contas a campanha necessariamente tem duração de 90 dias, depois disso **ninguém** mais pode comprar, não é? E se vender 90% dos ingressos apenas, como fica?

**Comment by ericdouglas** [comment]
@jeanleonino como estamos fazendo algo sem visar lucro, não tem necessidade de segurar ingressos, pois eles vão sempre ter o mesmo preço.

Se as pessoas não comprarem, simplesmente a conf não irá acontecer, pois parte da comunidade ter o interesse de participar do evento... Se não tem interessados o suficiente, é bem plausível não ocorrer o evento.

Acho que é algo nessa linha que estávamos conversando nas últimas reuniões.

**Comment by jeanleonino** [comment]
@ericdouglas mas **todos** (frisando) têm que comprar nos próximos 90 dias ou não vai ter nada? É isso que está um pouco estranho.

**Comment by thebergamo** [comment]
Acredito que seja isso mesmo @jeanleonino

**Comment by dalssoft** [comment]
@jeanleonino bem vindo novamente. E eu que fiquei off esses dias, mas agora to por aqui... e ai? bora marcar a próxima reunião pra fechar isso?

**Comment by dalssoft** [comment]
E ai? Vamos colocar esse projeto pra andar novamente? :)

**Comment by thebergamo** [comment]
Era uma boa! Tem um carinha aqui na empresa que já fez uma campanha no catarse, até o fim da semana quero sentar com ele e ver se conseguimos pelo menos começar.

**Comment by dalssoft** [comment]
Legal. Acho que já temos o formato, agora é colocar em prática. Vamos marcar uma reunião semana que vem pra dar sequência e não ficarmos parado. Que tal? Segunda (01/06) fica bom? Pode ser via hangout mesmo.

**Comment by thebergamo** [comment]
Por mim ok!

**Comment by dalssoft** [comment]
@ericdouglas @jeanleonino @willianjedai @alanhoff @heitortsergent @gblmarquez

**Comment by ericdouglas** [comment]
Bora! :smile:

**Comment by thebergamo** [comment]
Eai vai rolar???

**Comment by dalssoft** [comment]
Vai sim. Vamos fazer por hangout, às 19h (como sempre)

**Comment by thebergamo** [comment]
Por mim perfeito!

Vamos fazer!

**Comment by ericdouglas** [comment]
Vou fazer o possível para chegar a tempo!

**Comment by ericdouglas** [comment]
Aguardando o link...

**Comment by dalssoft** [comment]
https://plus.google.com/hangouts/_/gwa2szya7d4wg5yr5oybw5nvpua

**Comment by dalssoft** [comment]
Ata de ontem:

Quem? @ericdouglas @thebergamo @gblmarquez @dalssoft

Revisamos alguns itens antes de criar a página no cartase:

(1) Metas:

Para a primeira edição pensamos que seremos extremamente bem sucedidos se conseguirmos 100 pessoas. Por isso, resolvemos ficar apenas com uma meta.

(2) Slots para pessoas. 

Criamos dois tipos de slots:
Colaboradores: não vão participar do evento, mas gostariam de colaborar de alguma forma. Colaborações menores de 10 a 30 reais.
Participante: vai ao evento. Depois de compararmos com os valores de outros eventos decidimos aumentar para R$ 280 o valor. Isso possibilitou também que não vamos mais precisar de patrocinadores.

(3) Slots para empresas. 

Achamos que o valor por pessoa de 280 reais é compatível com outros eventos de dois dias com apresentações internacionais. Dessa maneira, permite fazer um evento 100% viabilizado por pessoas para pessoas. 

Isso não exclui possíveis patrocínios de empresas para outros itens (camiseta, caneca, etc), mas a viabilidade seria totalmente feita por PF.

(4) Brindes. 

Reduzimos ainda mais a quantidade de brindes (sem caneca!) e focamos mais nas palestras.

Ainda não fechamos o formato de divulgação.


TODO List:

Marcos
- Pedir para os gringos gravar videos
- IBTA: Confirmado a data
- Call4paper

David
- Ata de hoje: Atualizar github 
- Reconfirmar custos das passagens

Próximos passos
- Criar a página no cartase e divulgar
- Gravar vídeo do grupo para promover o cartase

Próxima reunião 08/06 19:00

**Comment by ericdouglas** [comment]
@dalssoft perfeito!

Estou muito satisfeito com o formato que chegamos!

@thebergamo depois vamos conversar sobre a criação da página no Catarse, posso ficar responsável de escrever o texto lá, e depois todos ajudam a aprimorá-lo.

o/

**Comment by thebergamo** [comment]
Perfeito! @ericdouglas 

Já falei mandei email pros gringos. Abrirei o C4P amanhã, o @alanhoff está me ajudando a revisar os textos. 

Seria legal se o @gpedro pudesse ajudar a gente a botar o site no ar o mais rápido possível. @alanhoff sabe me dizer como faço pra deployar o site?

**Comment by dalssoft** [comment]
Pessoal, só uma informação pra ficar no radar:

BrasilJs - 2 dias de evento, 15 dias antes do NodeConfBr

Palestrantes:
Andreas Gal -CTO da Mozilla
Eric Schoffstall - Criador do Gulp
Brendan Eich - Criador do Javascript
Laurie Voss - CTO do npm
Sebastian McKenzie - Criador do BabelJS

R$240

http://www.eventick.com.br/braziljs-2015

**Comment by ericdouglas** [comment]
@dalssoft seria interessante fazer uma pesquisa nos grupos, pra saber a intenção de <strike>voto</strike> compra da galera?

Um typeform e tal... descontamos uns 90% do número de sim e vemos se rola deixar a mesma data ou mudar.

**Comment by thebergamo** [comment]
É, vai ser complicado ter o BrasilJS tão perto da NodeConf. :/

**Comment by thebergamo** [comment]
Entretanto o pessoal se levar em consideração algumas frustrações do ano passado em relação a não terem falado sobre Node.js pode ajudar em alguns preferirem a nodeconf. :/

**Comment by dalssoft** [comment]
Apenas em caráter de exercício criei uma planilha simulando 250 pessoas ("Meta 2" na planilha)

Problema: tem que pagar um lugar maior (15K?) e com isso tem que dar a luva upfront

Coisa boa: 4 gringos, para ficar mais competitivo com o BrasilJs. (4 gringos e apenas 250 pessoas e não 4 mil pessoas)

**Comment by thebergamo** [comment]
O que ferra é conseguir o lugar. Vou ver com algumas pessoas aqui uma nova tentativa.

Mas ai não sei se daria pra conseguir levantar toda a grana.

**Comment by dalssoft** [comment]
Foi mais pra exercitar... mas ficou claro que quanto mais pessoas, mais fácil trazer palestrante e ainda pagar um lugar grande. Começa ganhar escala...

Vamos tentar fechar isso hj.

**Comment by thebergamo** [comment]
Vamos falar hoje?

Tenho algumas boas e más noticias.

**Comment by dalssoft** [comment]
Srs., hj tem...

@ericdouglas @jeanleonino @willianjedai @alanhoff @heitortsergent @gblmarquez

**Comment by thebergamo** [comment]
Que horas @dalssoft ?

**Comment by dalssoft** [comment]
O de sempre... 19h

Havia marcado, mas acho que ficou no final e ninguém leu :/ 

Próxima vamos usar um evento no G+

**Comment by thebergamo** [comment]
Blz! Cara, não consigo ficar mais do que 19:30 hj. Tenho que colocar na faculdade... será que não rola adiantar?

**Comment by gpedro** [comment]
queria participar, vão fazer por hangout ?

**Comment by thebergamo** [comment]
Hangout!

**Comment by jeanleonino** [comment]
Eu vou acompanhar só as atas.

Jean.

**Comment by dalssoft** [comment]
https://plus.google.com/hangouts/_/g2djsmy6weu4dhcxfjljw6nl5ua

**Comment by dalssoft** [comment]
Ata

- Sobre o prazo 
Pensamos em extender o prazo de Setembro para Novembro dado que (1) está muito próximo e talvez não de tempo de executar tudo a tempo e (2) fica muito próximo do BrasilJS.

- Conversamos sobre a Meta 2, com 200/250 pessoas e 4 palestrantes internacionais

Para viabilizar essa meta é necessário que tenhamos 

(1) Cartase: O que acontece se atingirmos 150 pessoas contribuintes, ou seja, mais que a Meta 1 e menos que a Meta 2? Precisamos entender melhor esse cenário para mitigar riscos.

(2) Lugar para 200 pessoas sem custo: Até semana que vem algumas pessoas vão tentar encontrar esses lugares e dar um update sobre isso na próxima semana.

Temos o prazo limite de go/no-go da meta 2 de uma semana. Na próxima semana iremos fechar isso.

TODO List:

@gblmarquez
- Conversar no Cartarse sobre Metas
- Falar com Faculdade Rio Branco

@thebergamo 
- Validar qualidade da apresentação do palestrante da Colombia
- Trazer opções para palestrantes internacionais (Gui ajuda)

@dalssoft
- Falar com Centro Cultural Sao Paulo, Cryptorave e FIAP

@guisouza 
- Falar com PUC Consolação

Próxima reunião 15/06 19:00
https://plus.google.com/events/cojgqudl7kilfovt3ac6rvtnidk

**Comment by dalssoft** [comment]
@estudio86 preciso do logo em alta para montar a apresentação do evento... pode disponibilizar? tks

**Comment by gblmarquez** [comment]
Pessoal, 

@willianjedai @dalssoft @gpedro @ericdouglas @heitortsergent @thebergamo @jeanleonino @guisouza

Vejam o feedback que recebi do pessoal do Catarse.

Não é possivel definir uma meta baseada em número de apoiadores, apenas valor arrecadado. A meta tem que ser financeira.

E a gente também não consegue reembolsar apenas parte dos apoiadores. O reembolso só acontece quando o projeto não atinge o valor necessário para ser realizado (a meta financeira).

O que a gente pode fazer pra sua ideia funcionar?
R: Meta estendida, Limite de Recompensa e Gatilho

#### 1. Meta Estendida
Vou dar um exemplo (beem fictício rs) pra te mostrar como elas podem ser usadas a seu favor:

Você determina que a sua meta mínimima (oficial) no Catarse é arrecadar R$1.000 e comunica (na descrição do projeto) que se conseguir arrecadar mais, chegando a R$2.000 você vai dobrar o tamanho do evento e o número de convidados internacionais. Ou seja:

Meta mínima/oficial: você precisa arrecadar R$1.000 para realizar um evento para 100 pessoas com 2 palestrantes internacionais.

Meta estendida/sugerida: você precisa arrecadar R$2.000 para realizar um evento para 200 pessoas com 4 palestrantes internacionais.

Como o Catarse trabalha com o modelo Tudo ou Nada de arrecadação:

Se ao fim do prazo você arrecadar menos que R$1.000: Nada - você não recebe nada, o Catarse não cobra nada e todo o dinheiro volta para os apoiadores.

Se ao fim do prazo você arrecadar R$1.000 ou mais: Tudo - você recebe o dinheiro (descontados 13% de taxa do Catarse). Ou seja, se você arrecadar qualquer valor acima de R$1.000 você vai receber o dinheiro. Por exemplo:

se ao fim do prazo você arrecadar R$1.500 você bateu a sua meta mínima, mas não chegou na meta estendida. Isso significa que você vai receber o dinheiro e está comprometido a entregar apenas o evento garantido pela arrecadação de pelo menos R$1.000.

#### 2. Limite de Recompensa

Pra garantir que você não ultrapasse a capacidade do evento você pode oferecer diferentes recompensas para quem contribuir financeiramente com o projeto, sendo que apenas uma delas garante entrada para as palestras.

Essa recompensa que garante a entrada para a palestra pode ser limitada para um numero máximo de apoiadores.

Como sua meta inicial garante um evento para até 100 pessoas, o número máximo de apoiadores para essa recompensa tem que ser igual a 100.

#### 3. Gatilho

Na descrição, junto com as sua meta estendida você pode comunicar que se (apenas se) vocês conseguirem chegar a R$2.000 serão distribuídas mais 100 vagas para determinados apoiadores.

Você pode definir esse gatilho logo no lançamento da campanha, ou depois que já tiver atingido a meta oficial.

E ai Gabriel, o que acha desse combo de estratégias? Funciona pra vocês?

Qualquer dúvida escreve aqui pra mim que eu te ajudo!
Abração,

PS - já viram o projeto da [CryptoRave](https://www.catarse.me/pt/CryptoRave2015)? Pode ser uma boa fonte de inspiração =)

**Comment by gblmarquez** [comment]
Pessoal,
@willianjedai @dalssoft @gpedro @ericdouglas @heitortsergent @thebergamo @jeanleonino @guisouza

Vocês tem algum feedback sobre as opções?

**Comment by thebergamo** [comment]
Acho que a última parece mais interessante!

**Comment by heitortsergent** [comment]
Na verdade a ideia é usar essas 3 coisas em conjunto, certo? :)

E acho que funciona bem pra NodeConf.

**Comment by dalssoft** [comment]
Reunião remarcada pra quarta:
https://plus.google.com/u/0/events/cojgqudl7kilfovt3ac6rvtnidk

**Comment by gblmarquez** [comment]
Mais infos do catarse
1. Metas estendidas
Olha esse exemplo aqui:
https://www.catarse.me/pt/ciclanoseciclanas
3. Gatilho
Olha esse exemplo aqui:
https://www.catarse.me/pt/naviodragao

**Comment by dalssoft** [comment]
Ata

- Lugar: Faculdade Rio Branco
  - 300 lugares

- Catarse
  - Vamos no modelo meta mínima, com gatilhos
  - Meta 1: 100 pessoas - 2 gringos
  - Meta 2: 200 pessoas - 4 gringos
  - Meta 3???

  Em caso de metas intermediárias (Ex: 150 pessoas), vamos ter que criar algo.

  - Dois slots para ingressos
    - 280 reais, limitado para 100 pessoas
    - 300 reais, até 200 pessoas

Próximos passos:
- Criar página no Cartase
- Plano de divulgação

Próxima segunda, mesmo horário:
https://plus.google.com/events/coh8tjrfi7esvjllluiq5f424a8

**Comment by thebergamo** [comment]
Já criei a página no Cartase precisamos apenas definir os textos e a campanha em si para podermos tocar isso =D

**Comment by gblmarquez** [comment]
Definição do espaço que temos acesso na FRB: auditorio para 230 lugares com WIFI e audio com a possibilidade de fazermos transmissão para mais uma sala de 60 lugares.

**Comment by thebergamo** [comment]
Dá pra fazer a transmissão no auditorio e + uma sala ou só da sala?

**Comment by gblmarquez** [comment]
Eu copiei o que ele escreveu, o que entendi é: temos uma sala para 230 lugares e caso necessário temos podemos usar + uma sala para 60 pessoas com transmissão ao vivo do que está acontecendo no auditorio.

**Comment by thebergamo** [comment]
Ahh agora entendi! bacana!

Quando ficou a data?

**Comment by gblmarquez** [comment]
Mesma de que definimos 5 e 6 de setembro
https://docs.google.com/spreadsheets/d/18_3oHtJ4exOieBTM5FTUPnnbG_SDuNm0dofQW1jYG2E/edit

**Comment by gblmarquez** [comment]
Temos agora também a oportunidade de fazer um meetup no final de agosto, @alanhoff como posso publicar isso no meetup?

**Comment by thebergamo** [comment]
não vai ficar em cima pro crowdfunding?

**Comment by suissa** [comment]
E ai como estao as coisas? Mto interessante essa ideia do crowdfunding!!!

**Comment by heitortsergent** [comment]
@thebergamo vai ficar em cima, mais dá pra fazer. :)

Temos aí 2 meses e meio pra organizar as coisas. Quais informações nós precisamos definir pra por o Catarse no ar?

**Comment by thebergamo** [comment]
Então bora botar a mão na massa hoje!!

Acredito que teremos uma reunião hoje as 19h certo? Poderia participar @heitortsergent ?

**Comment by heitortsergent** [comment]
Posso sim, tem link já?

**Comment by thebergamo** [comment]
Não sei, @dalssoft podia ajudar a gente nessa =D

**Comment by dalssoft** [comment]
Ta ai: https://plus.google.com/events/coh8tjrfi7esvjllluiq5f424a8

Estou colocando o link já no final de todas as atas. ;)

**Comment by thebergamo** [comment]
Vlw @dalssoft  =D

**Comment by thebergamo** [comment]
Senhores to saindo pra casa, chegando lá entro =D Vou atrasar alguns minutos

**Comment by dalssoft** [comment]
Hangout+: https://plus.google.com/hangouts/_/event/coh8tjrfi7esvjllluiq5f424a8

**Comment by dalssoft** [comment]
Ata 22/06

O que muda:

Data: 07 e 08 de Novembro (esperando confirmação do Fac. Rio Branco) (com @gblmarquez )

Como entendemos que o planejamento está definido, vamos fechar essa issue. Abriremos outra para acompanhar a execução do crowdfunding.

Execução: Issue https://github.com/nodebr/nodeconfbr/issues/52

Hangout: https://plus.google.com/events/c96va5i47gl83b8peb8koojaqgo (não consegui colocar recorrente :disappointed: )
