### ISSUE TITLE
Call for Papers

### ISSUE THREAD

**Issue by thebergamo** [nodebr/nodeconfbr#48]
Galera, 

Quero abrir o call4papers para a NodeConfBR essa semana o que acham?

**Comment by ericdouglas** [comment]
http://br.nodeconf.org/

**Comment by tallesl** [comment]
Reparei que o evento está também no [Call4Paperz](http://call4paperz.com/events/nodeconfbr)... algum lugar *de preferência*?

**Comment by thebergamo** [comment]
Na verdade no call4paperz eu cancelei... ainda está aberto?

**Comment by tallesl** [comment]
Não sei...

Bem confuso, na mesma página está escrito:

> This event is not accepting new proposals.

e

> This event is ready to receive proposals!

**Comment by thebergamo** [comment]
kkk Bug no site :p ele estava aberto, mas depois decidimos mudar.

**Comment by brunobelarmino** [comment]
galera mandei uma palestra hoje la no call for papers e achei algumas coisas ruins la:
- quantidade de caracteres do campo descrição da palestra (que vai pro site) - achei pequeno
- quantidade de caracteres do campo mini biografia - achei pequeno 300 caracteres somente

e quando finaliza o cadastro a mensagem de sucesso falando que o call for papaers fecha dia 01/07.
