### ISSUE TITLE
Patrocinadores

### ISSUE THREAD

**Issue by alanhoff** [nodebr/nodeconfbr#5]
Qual o modelo de patrocínio que vocês acham interessante? Eu acharia bacana se cada patrocinador arcasse com uma determinada despesa do evento ao invés de dar dinheiro, exemplo: Empresa X traz palestrante Y, Empresa A instala câmeras e microfones, empresa B aluga o espeço.

O que vocês acham?

**Comment by joaostein** [comment]
@alanhoff @guisouza Quando forem buscar patrocinadores me dêem um ping que talvez posso ajudar vocês. Se quiserem saber mais detalhes, entrem em contato joaosteing@gmail.com

**Comment by marcosbergamo** [comment]
Estávamos conversando aqui na empresa na qual eu trabalho e assim que definirmos o modelo de patrocínio, já podem contar com a mesma =D
