### ISSUE TITLE
Palestrantes Internacionais - Fechar nomes 

### ISSUE THREAD

**Issue by dalssoft** [nodebr/nodeconfbr#50]
- Entrar em contato com nomes relevantes da comunidade internacional Node 
- Pedir confirmação
- Pedir video 

@thebergamo tá com essa task

**Comment by dalssoft** [comment]
NodeConf Oneshot Oslo 2015
https://www.youtube.com/playlist?list=PLU1Iy0GYsI-r5DYwpNaxquBmaYaxZINYo

**Comment by dalssoft** [comment]
Sugestão:  Rod Vagg

https://www.youtube.com/watch?v=hZJCnT7E1ts

https://medium.com/@nodesource/the-state-of-node-in-the-enterprise-e513fbc0bdc

**Comment by thebergamo** [comment]
Rod Vagg é mto bom!!

O mikael não poderá vir :(

**Comment by thebergamo** [comment]
1 - Forest L. Novell - NPM (Confirmado)
2 - Julian Duque - NodeBots (Confirmado)

Para a meta dois acho que seria legal o Rod Vagg
