### ISSUE TITLE
Catarse - Texto da campanha

### ISSUE THREAD

**Issue by dalssoft** [nodebr/nodeconfbr#51]
@thebergamo vai disponibilizar um GDocs com o texto que será usando na campanha do Catarse

https://docs.google.com/document/d/1E_yavwYeEo5hwK0vLA_nnTR2zCuZY00_v8_XVDxUhno/edit?usp=sharing

**Comment by thebergamo** [comment]
Link disponibilizado!

**Comment by ericdouglas** [comment]
Vamos criar um .md aqui nesse repo... Melhor para ter controle.

**Comment by thebergamo** [comment]
Cara, não precisa disso. Só ir editando lá é mais fácil

**Comment by ericdouglas** [comment]
Mais fácil/eficiente que git + github para várias pessoas poderem editar o mesmo arquivo não tem.

E qualquer um pode ver e sugerir alterações.

**Comment by heitortsergent** [comment]
@thebergamo amanhã eu vou dar uma olhada nisso :). Vou mexer no GDocs mesmo

**Comment by thebergamo** [comment]
Nem sempre abrir o editor de texto é a melhor opção hehe. @heitortsergent blz qualquer coisa estou online o dia todo =D

**Comment by dalssoft** [comment]
lembrando que o GDocs guarda versão tb.

eu confesso que tentei começar o texto mas é mais difícil do que parece. :/

conseguimos ter um rascunho até amanhã? com o texto pronto posso pedir para amigos do mkt que tem conhecimento em eventos pra fazer um "text review".

**Comment by thebergamo** [comment]
Será que não podemos brincar com ele na hora da reunião? Acho que facilita tb!
