### ISSUE TITLE
Crowdfunding - Execução

### ISSUE THREAD

**Issue by dalssoft** [nodebr/nodeconfbr#52]
:white_medium_square: Palestrantes Internacionais - Fechar nomes - Issue https://github.com/nodebr/nodeconfbr/issues/50
:white_medium_square: Catarse - Texto da campanha - Issue https://github.com/nodebr/nodeconfbr/issues/51
:white_medium_square: Call 4 Paper - Issue https://github.com/nodebr/nodeconfbr/issues/48

Para referência rápida:

Texto Catarse - https://docs.google.com/document/d/1E_yavwYeEo5hwK0vLA_nnTR2zCuZY00_v8_XVDxUhno/edit

Planilha de custo - https://docs.google.com/spreadsheets/d/18_3oHtJ4exOieBTM5FTUPnnbG_SDuNm0dofQW1jYG2E/edit#gid=0

**Comment by dalssoft** [comment]
Hangout: https://plus.google.com/u/0/events/c96va5i47gl83b8peb8koojaqgo/108345064538342886853

**Comment by candreva** [comment]
Quanto custa o evento?

Qual o propósito?

**Comment by guisouza** [comment]
Luiz, esses dados podem ser encontrados no documento anexo a issue #51 
estamos trabalhando, eu e o @thebergamo em cima do texto do conceito (propósito) 
para anexar lá . 

muito inicialmente, estou tentando me apoiar no conceito "knowledge frees" ou  "Conhecimento Liberta" em tupiniquim claro..

**Comment by dalssoft** [comment]
@candreva atualizei o header da issue com a planilha de custo
