### ISSUE TITLE
Logotipo

### ISSUE THREAD

**Issue by alanhoff** [nodebr/nodeconfbr#6]
Eu curti o logotipo do @guisouza, se alguém quiser tentar outro..

@guisouza, consegue fazer uma versão desse logotipo na horizontal pra ficar bonito em headers e etc?

**Comment by jeanleonino** [comment]
@estudio86 use fontes do Google Fonts, que tal? É aberto, fácil de instalar :) e já são open source :) tem umas bem boas lá.

**Comment by jeanleonino** [comment]
@estudio86 é bem simples: para cada fonte você tem uma licença de uso para pagar. Existem licenças que são gratuitas, abertas. Outras são pagas. No caso as fontes que passou são pagas, não poderíamos usar em um evento desses sem pagar antes :-)

**Comment by estudio86** [comment]
@jeanleonino Ah legal, vou dar uma olhada aqui e testar outras, posto aqui quando finalizar. Valeu! =D

**Comment by jeanleonino** [comment]
@estudio86 legal! A Open Sans provavelmente é a mais usada, mas também tem a roboto e outras:

![webfonts_google_fontface_opensans](https://cloud.githubusercontent.com/assets/1311402/5942294/bb821716-a6fd-11e4-801f-9db6e17db2ff.jpg)
![webfonts_google_fontface_lato](https://cloud.githubusercontent.com/assets/1311402/5942289/b773ea82-a6fd-11e4-9c86-4df3cc20d05f.jpg)
![webfonts_google_fontface_josefinslab](https://cloud.githubusercontent.com/assets/1311402/5942298/be966092-a6fd-11e4-92e1-ce8cd72a2e27.jpg)

Mas... Também, caso o estúdio tenha a licença para utilizarmos, não há problema mantermos assim, mas vai da decisão da comunidade se quer utilizar algo que não seja open source.

**Comment by fernandoGuisso** [comment]
Eu acho q devia manter a fonte e o responsavel arrumar a licença ja que foi o aprovado, pq se for pra fazer um nova versão, com outra fonts, tem que reabrir o espaço pra outras pessoas denovo, tem my gente que não conseguiu mandar a tempo.

**Comment by jeanleonino** [comment]
@fernandoGuisso ao se manter a fonte, teríamos que pagar pela licença para customizações que a organização queira fazer... E fere também o espírito open-source do projeto. Visto que o logo não será refeito, mas apenas adaptado... Não acho que seria um grande problema.

**Comment by alanhoff** [comment]
+1 jean...


--
Alan Hoffmeister
https://twitter.com/alan_hoff
https://github.com/alanhoff
https://keybase.io/alanhoff

Em 28 de janeiro de 2015 15:39, Jean <notifications@github.com> escreveu:

**Comment by estudio86** [comment]
Tenho uma licença da fonte, porém, além de achar que vai contra o espírito open-source do projeto, creio que seria necessário comprar outra, para as devidas customizações, assim como o @jean falou. Acho que seria legal só mudar a fonte mesmo. É tranquilo achar alguma fonte parecida.

**Comment by jeanleonino** [comment]
Legal, @estudio86! Precisando de algo mais é só dizer! Estou aqui agora para te ajudar nessa parte visual.

**Comment by alanhoff** [comment]
Qualquer coisa podem consultar estes sites, os dois primeiros são de fontes open-source e o último é de fontes livres para uso comercial

https://www.google.com/fonts
http://openfontlibrary.org/
http://www.fontsquirrel.com/

**Comment by jeanleonino** [comment]
Ahh, o font squirrel tem bem mais opções, @estudio86!

Jean.

**Comment by jeanleonino** [comment]
@estudio86 tem como enviar por agora? Precisamos lançar a landing page e começar a captar dinheiro.

**Comment by estudio86** [comment]
Opa pessoal, desculpa a demora.

Mudamos a fonte do logotipo conforme falamos aqui, inclusive eu enviei outro dia para o @marcosbergamo, mas fiquei de mandar mais coisas e acabei me enrolando aqui no trampo.

Segue o logo com a fonte Armata (Open Source), vocês vão notar que ficou praticamente igual ao aprovado anteriormente.

![captura de tela 2015-03-02 as 22 03 37](https://cloud.githubusercontent.com/assets/5941705/6454415/1684a612-c128-11e4-9d6c-e0aff1b6ac54.png)

--

A Landing Page também já está com o layout pronto, segue o link: http://estudio86.com.br/clientes15/nodeconfbr/

Os conteúdos são genéricos né? Por favor, me digam o que acham.

--

Vou postar aqui também alguns materiais de apoio, como Camisetas:
![camiseta-node-01](https://cloud.githubusercontent.com/assets/5941705/6454418/21bd1622-c128-11e4-9030-2ed00181c182.jpg)

![camiseta-node-02](https://cloud.githubusercontent.com/assets/5941705/6454419/21c1d8ec-c128-11e4-8bb2-ad0262458161.jpg)

E canecas:

![caneca-node-01](https://cloud.githubusercontent.com/assets/5941705/6454431/355a4efc-c128-11e4-93af-265da4a9a6dc.jpg)

![caneca-node-02](https://cloud.githubusercontent.com/assets/5941705/6454432/355d5be2-c128-11e4-98e9-bb45b7168d32.jpg)

Espero que vocês gostem.

**Comment by alanhoff** [comment]
WOW! WOW! Onde eu compro a caneca? :D

**Comment by afucher** [comment]
*-* ficaram muito boas!

Se achar onde compra @alanhoff , compra uma pra mim! hahahah

**Comment by estudio86** [comment]
Então, tenho um fornecedor de canecas e camisetas, pensei que poderíamos fazer algumas para vender mesmo, e até, sortear, sei lá.

**Comment by alanhoff** [comment]
@estudio86 qual a quantidade mínima que podemos comprar?

**Comment by estudio86** [comment]
Então, caneca eu sei que não tem quantia mínima, se fizer mais, sai mais em conta, claro. Camiseta tem, mínimo de 50 peças, mas, meu fornecedor cobra bem abaixo, custando em média R$18,00 por camiseta, já incluindo o silk, as telas e as camisetas.

**Comment by marcosbergamo** [comment]
Caraca fantástico mesmo =D já tô querendo reservar a minha. Podemos fazer algumas canecas e camisetas personalizadas se rolar o crownfunding

**Comment by estudio86** [comment]
Seria legal né @marcosbergamo? Eu acho que são formas de fazer uma grana, pra ajudar no evento né?

**Comment by alanhoff** [comment]
Beleza pessoal, @estudio86 consegue fazer o upload do arquivo vetorial (ou do projeto), assim da pra fechar essa thread e continuar a organizar :-)

**Comment by marcosbergamo** [comment]
@estudio86 sim vai ser bem massa, acho que podemos fazer grandes coisas ai =D como o @alanhoff  falou ia ser bacana se você subisse o vetorial pra que pudêssemos manipular mais fácil as imagens =D

**Comment by estudio86** [comment]
Então, eu sou meio burro aqui no Git, caso eu não consiga subir aqui, posso mandar por e-mail @marcosbergamo? Qual formato seria legal? AI, PDF ou SVG mesmo?

Existe outros materiais que eu poderia ir montando pra adiantar @marcosbergamo e @alanhoff ?

**Comment by jeanleonino** [comment]
@estudio86, parabéns pelo trabalho.

Então, vamos focar em alguns pontos? Podemos marcar uma chamada só para
isso?

Formato ideal é AI e SVG!

Jean.

2015-03-02 22:38 GMT-03:00 estudio86 <notifications@github.com>:

**Comment by alanhoff** [comment]
@estudio86 vc não é burro cara hahaha

Pode me mandar por e-mail o SVG alanhoffmeister@gmail.com


--
Alan Hoffmeister
https://twitter.com/alan_hoff
https://github.com/alanhoff
https://keybase.io/alanhoff

Em 2 de março de 2015 22:38, estudio86 <notifications@github.com> escreveu:

**Comment by estudio86** [comment]
Valeu @jeanleonino, brigadão! O @alanhoff, eu apanho demais do Git haha ... Meu negócio é criação, não tem jeito. Blz, mando para você com cópia para o @marcosbergamo ter também. Com relação a Landing Page, o que acharam?

**Comment by marcosbergamo** [comment]
Eu achei super massa a landing =D

Fico no aguardo das imagens pra poder subir nas mídias sociais!

**Comment by jeanleonino** [comment]
@estudio86 legal, se não conseguir pelo git, manda o ai e o svg para alanhoff@gmail.com. :-) 

Vamos marcar uma conversa amanhã? Aí a gente fecha a landing page e etc.

**Comment by estudio86** [comment]
@marcosbergamo já te mandei no e-mail, não chegou ai?

**Comment by estudio86** [comment]
Podemos sim @jeanleonino, pode ser no skype? Amanhã estarei no escritório na parte da tarde, acho que depois das 16:00. Ou então, à noite, depois das 20:30. =D

**Comment by jeanleonino** [comment]
@estudio86 perfeito, meu skype é jeanleonino, vamos fechar muita coisa já :) 

Abs, até amanhã!

**Comment by estudio86** [comment]
Demoro, já está adicionado @jeanleonino

**Comment by estudio86** [comment]
@alanhoff Qual seu e-mail mesmo para mandar o logo Alan?

**Comment by estudio86** [comment]
Já mandei pro @alanhoff, @marcosbergamo e @jeanleonino Blz?

**Comment by alanhoff** [comment]
alanhoffmeister@gmail.com


--
Alan Hoffmeister
https://twitter.com/alan_hoff
https://github.com/alanhoff
https://keybase.io/alanhoff

2015-03-02 23:20 GMT-03:00 estudio86 <notifications@github.com>:

**Comment by jeanleonino** [comment]
Beleza.
