### ISSUE TITLE
Localização do evento

### ISSUE THREAD

**Issue by alanhoff** [nodebr/nodeconfbr#8]
Alguém tem ideia de onde podemos hospedar este evento? Acho que SP seria a cidade ideal para que ele ocorra visto que a grande maioria do público está localizada aqui, pelo menos é o que apontam os grupos do MeetUp.

**Comment by ctoveloz** [comment]
Concordo que seja em sampa mas discordo que seja em um sitio ou chacara, pro pessoal de outros estados vai complicar se locomover.

**Comment by obetomuniz** [comment]
Com relação a chácara, fico ainda incerto com relação a logística, visto que o evento é proposto para 200 pessoas, fora palestrantes e organização.

Entendo que é uma ótima ideia e totalmente fora da caixa do que vemos atualmente no Brasil, mas qual seria o principal motivo inicial de viabilizar essa edição dessa forma? Pois acredito que muitos dos que irão vir ao evento (palestrantes e participantes) ainda não conhecem São Paulo-Capital, ou seja, não precisamos ainda radicalizar a esse nível, apesar de que se bem planejado, não seria má ideia.

O que me preocupa, é a dependência de infra estrutura oferecida para o evento, palestrantes, organização e participantes de locais mais remotos ou do interior do Brasil, e não apenas onde vamos dormir.

Eu deixaria esta opção de chácara para uma edição posterior.
